export const chapters = [
  {
    id: 1,
    title: "Constitution de la matière - La mole",
    icon: "⚛️",
    color: "#38bdf8",
    definition: "La chimie quantitative s'appuie sur le concept de mole : une unité de comptage des entités chimiques (atomes, molécules, ions). La constitution de la matière décrit comment atomes et molécules s'assemblent, se comptent et se transforment.",
    formulas: [
      { name: "Nombre de moles", expr: "n = m / M", desc: "n (mol), m (g), M (g/mol)" },
      { name: "Nombre d'entités", expr: "N = n × Nₐ", desc: "Nₐ = 6,022 × 10²³ mol⁻¹" },
      { name: "Concentration molaire", expr: "C = n / V", desc: "C (mol/L), V (L)" },
      { name: "Concentration massique", expr: "Cm = m / V", desc: "Cm (g/L)" },
      { name: "Relation masse volumique", expr: "ρ = m / V", desc: "ρ (g/mL ou kg/L)" },
      { name: "Dilution", expr: "C₁V₁ = C₂V₂", desc: "Avant = Après dilution" },
    ],
    demonstrations: [
      "Établissement de la relation n = m/M à partir de la définition de la masse molaire.",
      "Calcul du nombre d'entités à partir de la masse : N = (m/M) × Nₐ.",
      "Démonstration de la loi de dilution : conservation des moles de soluté.",
    ],
    schemas: [
      `Tableau d'avancement :\n\nÉquation :  aA + bB → cC + dD\nÉtat init. : n(A)₀  n(B)₀    0    0\nÉtat x   : n(A)₀-ax n(B)₀-bx  cx   dx\nÉtat final: n(A)f   n(B)f    n(C)f n(D)f`,
    ],
    tips: [
      "Toujours identifier M (masse molaire) depuis le tableau périodique. Attention aux formules polyatomiques (ex: H₂O → M = 18 g/mol).",
      "En dilution, noter clairement C₁, V₁ (solution mère) et C₂, V₂ (solution fille).",
      "Le tableau d'avancement est INCONTOURNABLE pour tout bilan molaire.",
    ],
    remember: [
      "1 mole = 6,022 × 10²³ entités (nombre d'Avogadro).",
      "n = m/M est la formule de base à maîtriser parfaitement.",
      "Dilution : les moles de soluté se conservent (C₁V₁ = C₂V₂).",
    ],
  },
  {
    id: 2,
    title: "Suivi temporel - Cinétique chimique",
    icon: "⏱️",
    color: "#a78bfa",
    definition: "La cinétique chimique étudie la vitesse à laquelle se déroulent les réactions chimiques. Elle permet de suivre l'évolution d'un système au cours du temps et d'identifier les facteurs qui influencent cette vitesse.",
    formulas: [
      { name: "Vitesse volumique de réaction", expr: "v = (1/V) × (dx/dt)", desc: "x : avancement (mol), V : volume (L)" },
      { name: "Vitesse en concentration", expr: "v = d[P]/dt = -d[R]/dt", desc: "Pour les coefficients stœchiométriques = 1" },
      { name: "Temps de demi-réaction", expr: "t₁/₂ : [A](t₁/₂) = [A]₀/2", desc: "Lecture graphique ou calcul" },
      { name: "Loi de vitesse (ordre 1)", expr: "[A](t) = [A]₀ × e^(-kt)", desc: "k : constante de vitesse (s⁻¹)" },
      { name: "Loi d'Arrhénius", expr: "k = A × e^(-Eₐ/RT)", desc: "Eₐ : énergie d'activation, R = 8,314 J/mol/K" },
    ],
    demonstrations: [
      "Détermination graphique de la vitesse instantanée : tangente à la courbe [P](t) ou [R](t).",
      "Détermination du temps de demi-réaction par lecture graphique.",
      "Influence de la température sur k via la loi d'Arrhénius : ln(k) = -Eₐ/RT + ln(A).",
    ],
    schemas: [
      `Courbe cinétique :\n\n[Réactif]\n   |\n[A]₀ |\\  \n     | \\ \n[A]₀/2|--+------\n     |    \\    \n     |     \\___\n     +--+-------→ t\n           t₁/₂`,
    ],
    tips: [
      "La tangente en t=0 donne la vitesse initiale (maximale). En t quelconque, tracer la tangente à ce point.",
      "Pour identifier l'ordre : si t₁/₂ est constant → ordre 1. Si t₁/₂ ∝ 1/[A]₀ → ordre 2.",
      "Loi d'Arrhénius : augmenter T de 10°C double souvent k (règle approximative).",
    ],
    remember: [
      "La vitesse de réaction est toujours positive et diminue au cours du temps.",
      "Le temps de demi-réaction t₁/₂ est lu sur le graphe : quand [R] = [R]₀/2.",
      "Facteurs cinétiques : température ↑ → vitesse ↑ ; catalyseur → abaisse Eₐ.",
    ],
  },
  {
    id: 3,
    title: "Équilibres chimiques - Acide/Base",
    icon: "⚖️",
    color: "#34d399",
    definition: "Un équilibre chimique est un état dynamique où les vitesses des réactions directe et inverse sont égales. En chimie acido-basique, un acide est un donneur de proton (H⁺) et une base est un accepteur de proton (théorie de Brønsted).",
    formulas: [
      { name: "Constante d'équilibre", expr: "K = [C]^c[D]^d / ([A]^a[B]^b)", desc: "Sans dimension, dépend de T" },
      { name: "Constante d'acidité", expr: "Ka = [A⁻][H₃O⁺] / [HA]", desc: "Pour HA + H₂O ⇌ A⁻ + H₃O⁺" },
      { name: "pKa", expr: "pKa = -log(Ka)", desc: "Ka = 10^(-pKa)" },
      { name: "pH", expr: "pH = -log[H₃O⁺]", desc: "[H₃O⁺] = 10^(-pH)" },
      { name: "Produit ionique de l'eau", expr: "Ke = [H₃O⁺][OH⁻] = 10⁻¹⁴", desc: "À 25°C, pKe = 14" },
      { name: "Acide fort (pH)", expr: "pH = -log(Ca)", desc: "Acide fort totalement dissocié" },
      { name: "Base forte (pH)", expr: "pH = 14 + log(Cb)", desc: "Base forte totalement dissociée" },
      { name: "Taux d'avancement", expr: "τ = x_f / x_max", desc: "Réaction totale si τ = 1" },
    ],
    demonstrations: [
      "Démonstration de pH = -log(Ca) pour un acide fort (ex: HCl).",
      "Calcul du pH d'un acide faible : résolution de [H₃O⁺]² + Ka[H₃O⁺] - Ka·Ca = 0.",
      "Diagramme de prédominance : espèce acide prédominante si pH < pKa.",
    ],
    schemas: [
      `Diagramme de prédominance :\n\n  HA prédominante   |   A⁻ prédominante\n                    |\n  ←── pH < pKa ────pKa──── pH > pKa ──→\n                    |\n              [HA] = [A⁻]`,
    ],
    tips: [
      "Pour tout acide ou base, écrire d'abord la réaction avec l'eau, puis le tableau d'avancement, puis l'expression de Ka.",
      "Si pH << pKa → acide prédominant. Si pH >> pKa → base prédominante. À pH = pKa → concentrations égales.",
      "Pour un amphotère : pH ≈ (pKa1 + pKa2)/2.",
    ],
    remember: [
      "Acide = donneur H⁺ / Base = accepteur H⁺ (Brønsted). Toujours écrire le couple acide/base conjugué.",
      "pH = pKa ↔ [HA] = [A⁻]. C'est la définition graphique et quantitative du pKa.",
      "Ke = 10⁻¹⁴ à 25°C : milieu acide pH<7, basique pH>7, neutre pH=7.",
    ],
  },
  {
    id: 4,
    title: "Stratégies en synthèse organique",
    icon: "🧪",
    color: "#f472b6",
    definition: "La synthèse organique consiste à construire des molécules organiques par des transformations chimiques contrôlées. Elle requiert de choisir les réactions (substitution, addition, élimination, oxydation/réduction) et les conditions opératoires optimales.",
    formulas: [
      { name: "Rendement", expr: "η = n_obtenu / n_théorique × 100%", desc: "n en moles" },
      { name: "Réaction de substitution (SN)", expr: "R-X + Nu⁻ → R-Nu + X⁻", desc: "Nu : nucléophile, X : groupe partant" },
      { name: "Addition électrophile (AE)", expr: "R=R + E⁺ → R-R-E⁺ → R-R-E-Nu", desc: "Sur les alcènes" },
      { name: "Élimination (E2)", expr: "R-CH₂-CHX-R → R-CH=CH-R + HX", desc: "Base forte + chaleur" },
    ],
    demonstrations: [
      "Distinction entre substitution et élimination : facteurs favorisants (nucléophile fort = SN, base encombrée = E).",
      "Règle de Markovnikov : en addition HX sur un alcène asymétrique, H se fixe sur le C le plus H-substitué.",
      "Calcul du rendement à partir des masses obtenues et théoriques.",
    ],
    schemas: [
      `Étapes d'une synthèse :\n\n  Matières premières\n         ↓\n   [Réaction 1] → Solvant, T°, catalyseur\n         ↓\n   Produit brut\n         ↓\n   [Purification] → Filtration, distillation, recristallisation\n         ↓\n   Produit pur → Identification (IR, RMN, CCM)`,
    ],
    tips: [
      "Toujours identifier le groupe fonctionnel réactif avant de choisir le réactif.",
      "CCM : Rf = distance parcourue par le produit / distance parcourue par le solvant. Identifier par comparaison avec témoins.",
      "Rendement < 100% toujours en pratique : pertes lors des étapes de purification.",
    ],
    remember: [
      "Identifier la transformation à réaliser : addition, substitution, élimination, oxydation ou réduction.",
      "La purification est obligatoire : CCM, distillation, recristallisation selon l'état.",
      "Contrôle de l'identité du produit : spectre IR (groupes fonctionnels), RMN ¹H (environnement des H).",
    ],
  },
  {
    id: 5,
    title: "Description d'un mouvement",
    icon: "🏃",
    color: "#fbbf24",
    definition: "La cinématique décrit le mouvement sans s'intéresser à ses causes. Elle définit la position, la vitesse et l'accélération d'un objet dans un référentiel donné.",
    formulas: [
      { name: "Vecteur position", expr: "OM⃗ = x(t)⃗i + y(t)⃗j", desc: "En 2D dans un référentiel cartésien" },
      { name: "Vecteur vitesse", expr: "v⃗ = dOM⃗/dt", desc: "vx = dx/dt, vy = dy/dt" },
      { name: "Norme de la vitesse", expr: "|v⃗| = √(vx² + vy²)", desc: "En m/s" },
      { name: "Vecteur accélération", expr: "a⃗ = dv⃗/dt", desc: "ax = dvx/dt, ay = dvy/dt" },
      { name: "Équation horaire (MRUA)", expr: "x(t) = x₀ + v₀t + ½at²", desc: "v(t) = v₀ + at" },
    ],
    demonstrations: [
      "Passage de la courbe x(t) à v(t) par dérivation graphique (pente de la tangente).",
      "Détermination d'une trajectoire en éliminant le paramètre t entre x(t) et y(t).",
    ],
    schemas: [
      `Types de mouvements :\n\nMRU  : a = 0, v = cste  → trajectoire rectiligne\nMRUA : a = cste ≠ 0    → trajectoire parabolique (si 2D)\nMCU  : |v| = cste, a⊥v → trajectoire circulaire\n\nVecteur accélération :\n  ┌─ a tangentielle (variation de |v|)\na = │\n  └─ a normale (variation de direction)`,
    ],
    tips: [
      "La pente de v(t) donne l'accélération. La pente de x(t) donne la vitesse (MRU).",
      "Pour une trajectoire parabolique : écrire x(t) et y(t), puis exprimer t depuis x(t) et substituer dans y(t).",
      "Toujours préciser le référentiel et le repère choisis en début de problème.",
    ],
    remember: [
      "v⃗ = dOM⃗/dt et a⃗ = dv⃗/dt : dérivation par rapport au temps.",
      "MRU : vitesse constante, pas d'accélération. MRUA : accélération constante.",
      "La trajectoire est l'équation y = f(x) obtenue en éliminant t.",
    ],
  },
  {
    id: 6,
    title: "Deuxième loi de Newton",
    icon: "🍎",
    color: "#38bdf8",
    definition: "La deuxième loi de Newton (principe fondamental de la dynamique, PFD) relie la somme des forces extérieures agissant sur un système à son accélération. Elle est le cœur de la mécanique classique.",
    formulas: [
      { name: "PFD (2ème loi de Newton)", expr: "ΣF⃗ext = m × a⃗", desc: "m (kg), a⃗ (m/s²)" },
      { name: "Poids", expr: "P⃗ = m × g⃗", desc: "g ≈ 9,81 m/s² (vers le bas)" },
      { name: "Réaction normale", expr: "N⃗ : surface → objet, ⊥ surface", desc: "" },
      { name: "Friction", expr: "f = μ × N", desc: "μ : coefficient de frottement" },
      { name: "Tension d'un fil", expr: "T⃗ : dans la direction du fil", desc: "Fil tendu et inextensible" },
      { name: "Équation du mouvement", expr: "a = ΣF/m", desc: "Projection sur chaque axe" },
    ],
    demonstrations: [
      "Application du PFD sur un plan incliné : projection sur les axes x (∥ plan) et y (⊥ plan).",
      "Système de deux solides liés : le PFD s'applique à chaque solide séparément ou au système total.",
      "Établissement de l'équation différentielle du mouvement pour un oscillateur.",
    ],
    schemas: [
      `Plan incliné :\n\n         y ↑   N\n           \\   ↑\n            \\ /\n      P⃗sin α →●\n             / \\\n            /   ↓ P⃗\n    ________/____\n        α\n\nAxe x : ma = P sinα - f\nAxe y : 0  = N - P cosα`,
    ],
    tips: [
      "Toujours faire un schéma des forces avant d'écrire le PFD. Choisir les axes intelligemment (un axe dans la direction du mouvement).",
      "Si l'objet est en équilibre : ΣF⃗ = 0⃗ (1ère loi de Newton).",
      "Système de solides : additionner les équations pour trouver a, puis isoler les tensions.",
    ],
    remember: [
      "ΣF⃗ext = ma⃗ : TOUJOURS référencer au centre de masse, dans un référentiel galiléen.",
      "Projeter sur les axes : on obtient autant d'équations scalaires que d'axes.",
      "Si accélération nulle → soit immobile, soit mouvement rectiligne uniforme.",
    ],
  },
  {
    id: 7,
    title: "Mouvement dans un champ de pesanteur",
    icon: "🪂",
    color: "#a78bfa",
    definition: "Dans un champ de pesanteur uniforme, la seule force exercée sur un projectile est son poids (on néglige les frottements). Ce mouvement est une composition d'un MRU horizontal et d'un MRUA vertical.",
    formulas: [
      { name: "Équations horaires", expr: "x(t) = v₀cosθ·t\ny(t) = v₀sinθ·t - ½gt²", desc: "Lancé à v₀ et angle θ" },
      { name: "Composantes de vitesse", expr: "vx(t) = v₀cosθ\nvy(t) = v₀sinθ - gt", desc: "" },
      { name: "Équation de trajectoire", expr: "y = x·tanθ - gx²/(2v₀²cos²θ)", desc: "Parabole" },
      { name: "Portée maximale", expr: "xmax = v₀²sin(2θ)/g", desc: "Maximale pour θ = 45°" },
      { name: "Hauteur maximale", expr: "hmax = v₀²sin²θ/(2g)", desc: "Quand vy = 0" },
    ],
    demonstrations: [
      "Démonstration que la trajectoire est une parabole : exprimer t = x/(v₀cosθ), substituer dans y(t).",
      "Calcul de la portée : y = 0 → trouver t de chute → porter dans x(t).",
      "Démonstration que la portée est maximale pour θ = 45° : dxmax/dθ = 0.",
    ],
    schemas: [
      `Chute parabolique :\n\n  y\n  ↑         ●\n  |        / \\\n  |       /   \\\n  |      /     \\\n  |  θ  /       \\\n  | ←→ /         \\\n  +---●-----------●-→ x\n    v₀              portée\n\n  vx = cste   vy = v₀sinθ - gt`,
    ],
    tips: [
      "Chute libre verticale (θ=90°) : y(t) = h - ½gt² → temps de chute t = √(2h/g).",
      "Lancer horizontal (θ=0°) : x = v₀t et y = -½gt². Trajectoire : y = -gx²/(2v₀²).",
      "La portée est symétrique : angle θ et angle (90°-θ) donnent la même portée.",
    ],
    remember: [
      "Horizontalement : MRU (vx constant). Verticalement : MRUA (accélération = -g).",
      "La trajectoire est une parabole (sauf lancé vertical).",
      "Portée max pour θ = 45° uniquement si le sol est horizontal et au même niveau.",
    ],
  },
  {
    id: 8,
    title: "Mouvement dans un champ électrostatique uniforme",
    icon: "⚡",
    color: "#f472b6",
    definition: "Dans un champ électrique uniforme E⃗ (entre deux plaques parallèles par exemple), une particule chargée subit une force électrique F⃗ = qE⃗. Le mouvement est analogue au mouvement dans un champ de pesanteur.",
    formulas: [
      { name: "Force électrique", expr: "F⃗ = q × E⃗", desc: "q (C), E (V/m ou N/C)" },
      { name: "Champ entre plaques", expr: "E = U_AB / d", desc: "U (V), d : distance entre plaques (m)" },
      { name: "Accélération", expr: "a = qE/m", desc: "Selon l'axe du champ" },
      { name: "Équations horaires (champ vertical)", expr: "x(t) = v₀t\ny(t) = ½(qE/m)t²", desc: "Entrée horizontale à v₀" },
      { name: "Déviation transversale", expr: "y = qE·x² / (2mv₀²)", desc: "Parabole" },
      { name: "Énergie cinétique gagnée", expr: "ΔEC = q × U_acc", desc: "Si particule accélérée par U_acc" },
    ],
    demonstrations: [
      "Démonstration que la trajectoire entre les plaques est une parabole (analogue au projectile).",
      "Calcul de la déviation en sortie des plaques : y_sortie = qEL²/(2mv₀²) avec L = longueur des plaques.",
      "Application du théorème énergie-travail : ΔEC = q·U_acc pour l'accélération.",
    ],
    schemas: [
      `Condensateur plan :\n\n  + + + + + + +\n  ________________\n  →→→→●→→→→→→\n  v₀   ↓ F=qE (si q>0, E vers bas)\n  ________________\n  - - - - - - -\n  |←──── L ────→|\n\n  Trajectoire parabolique entre les plaques`,
    ],
    tips: [
      "Analogie complète avec le projectile : vx = v₀ = cste, vy = (qE/m)t.",
      "Si la charge est négative (électron), la force est opposée au champ.",
      "Énergie : ½mv₀² + qU_acc = ½mv_sortie² (conservation énergie si seul le champ électrique agit).",
    ],
    remember: [
      "F⃗ = qE⃗ : la force est parallèle au champ pour une charge positive, antiparallèle pour une négative.",
      "E = U/d pour un condensateur plan (champ uniforme entre les plaques).",
      "Mouvement : MRU perpendiculaire au champ, MRUA parallèle au champ.",
    ],
  },
  {
    id: 9,
    title: "Mouvement des satellites - Lois de Kepler",
    icon: "🛸",
    color: "#34d399",
    definition: "Les lois de Kepler décrivent le mouvement des planètes et satellites dans le champ gravitationnel. La gravitation universelle de Newton unifie ces lois et permet de calculer vitesses, périodes et altitudes orbitales.",
    formulas: [
      { name: "Gravitation universelle", expr: "F = G × m₁m₂ / r²", desc: "G = 6,674×10⁻¹¹ N·m²/kg²" },
      { name: "3ème loi de Kepler", expr: "T² / a³ = 4π² / (GM)", desc: "M = masse corps central, a = demi-grand axe" },
      { name: "Orbite circulaire (vitesse)", expr: "v = √(GM/r)", desc: "r = rayon orbite" },
      { name: "Orbite circulaire (période)", expr: "T = 2πr / v = 2π√(r³/GM)", desc: "" },
      { name: "Vitesse de libération", expr: "v_lib = √(2GM/R)", desc: "R = rayon de la planète" },
      { name: "Énergie mécanique orbitale", expr: "Em = -GMm / (2r)", desc: "Orbite circulaire" },
    ],
    demonstrations: [
      "Démonstration de la 3ème loi de Kepler pour une orbite circulaire : PFD → ΣF = mv²/r → T²/r³ = 4π²/(GM).",
      "Calcul de la vitesse orbitale : F_grav = F_centripète → GMm/r² = mv²/r → v = √(GM/r).",
      "Satellite géostationnaire : T = 24h → calcul de r et de l'altitude h = r - R_Terre.",
    ],
    schemas: [
      `1ère loi de Kepler (orbite elliptique) :\n\n         *           *\n      *               *\n    *                   *\n    *    ●Foyer    ●    *\n    *   Planète(+peri) *\n      *               *\n         *           *\n\n2ème loi : aires balayées égales en temps égaux\n3ème loi : T²/a³ = constante pour tous les corps\n           orbitant autour du même astre`,
    ],
    tips: [
      "Pour un satellite géostationnaire : T = 24h = 86 400 s. Attention aux unités !",
      "L'orbite circulaire est un cas particulier de l'ellipse (excentricité e = 0).",
      "PFD pour satellite : F_grav = F_centripète. Ne pas oublier que r = R_planète + altitude.",
    ],
    remember: [
      "3 lois de Kepler : orbites elliptiques / loi des aires (égales) / T²/a³ = constante.",
      "Pour une orbite circulaire : v = √(GM/r) et T² = 4π²r³/(GM).",
      "Satellite géostationnaire : T = 24h, orbite équatoriale, altitude ≈ 36 000 km.",
    ],
  },
  {
    id: 10,
    title: "Description d'un système thermodynamique - Gaz parfait",
    icon: "🌡️",
    color: "#fbbf24",
    definition: "La thermodynamique décrit les échanges d'énergie (chaleur, travail) dans les systèmes macroscopiques. Le modèle du gaz parfait suppose des molécules ponctuelles sans interactions entre elles.",
    formulas: [
      { name: "Équation d'état des gaz parfaits", expr: "PV = nRT", desc: "R = 8,314 J/(mol·K), T en Kelvin" },
      { name: "Conversion température", expr: "T(K) = θ(°C) + 273,15", desc: "" },
      { name: "Loi de Boyle-Mariotte", expr: "P₁V₁ = P₂V₂", desc: "À T constante (isotherme)" },
      { name: "Loi de Gay-Lussac", expr: "P₁/T₁ = P₂/T₂", desc: "À V constant (isochore)" },
      { name: "Loi de Charles", expr: "V₁/T₁ = V₂/T₂", desc: "À P constante (isobare)" },
      { name: "Énergie interne gaz parfait monoatomique", expr: "U = (3/2)nRT", desc: "Dépend uniquement de T" },
    ],
    demonstrations: [
      "Démonstration des lois de Boyle, Gay-Lussac et Charles à partir de PV = nRT.",
      "Justification que l'énergie interne d'un gaz parfait ne dépend que de T (pas de P ou V).",
      "Calcul du volume molaire à T et P données : Vm = RT/P.",
    ],
    schemas: [
      `Diagramme PV :\n\n  P\n  ↑\n  |  T₃ > T₂ > T₁\n  | \\  (isothermes PV=cste)\n  |  T₃\\\n  |     T₂\\\n  |        T₁\\\n  +-------------→ V\n\nP↑ quand T↑ (à V constant)\nV↑ quand T↑ (à P constant)`,
    ],
    tips: [
      "Toujours convertir les températures en Kelvin avant tout calcul !",
      "Conditions normales (CNTP) : T = 273,15 K (0°C) et P = 101 325 Pa → Vm = 22,4 L/mol.",
      "Si deux variables changent simultanément : utiliser PV/T = nR = constante.",
    ],
    remember: [
      "PV = nRT : la loi fondamentale du gaz parfait. R = 8,314 J/(mol·K).",
      "T en Kelvin OBLIGATOIRE : T(K) = T(°C) + 273.",
      "Gaz parfait : pas d'interactions entre molécules, énergie interne ∝ T seulement.",
    ],
  },
  {
    id: 11,
    title: "Bilans d'énergie - Premier principe",
    icon: "🔥",
    color: "#38bdf8",
    definition: "Le premier principe de la thermodynamique est la loi de conservation de l'énergie : l'énergie interne d'un système varie selon les échanges de chaleur et de travail avec l'extérieur.",
    formulas: [
      { name: "Premier principe", expr: "ΔU = W + Q", desc: "W : travail reçu, Q : chaleur reçue (algébriques)" },
      { name: "Travail des forces de pression", expr: "W = -P_ext × ΔV", desc: "Transformation quasi-statique" },
      { name: "Capacité thermique", expr: "Q = m × c × ΔT", desc: "c : chaleur massique (J/kg/K)" },
      { name: "Capacité molaire à P constant", expr: "Q = n × Cp × ΔT", desc: "" },
      { name: "Transformation isotherme GP", expr: "ΔU = 0 → W = -Q", desc: "Gaz parfait, T constante" },
      { name: "Enthalpie", expr: "H = U + PV → ΔH = Q_P", desc: "Chaleur échangée à P constant" },
    ],
    demonstrations: [
      "Transformation adiabatique : Q = 0 → ΔU = W (tout le travail → énergie interne).",
      "Calcul du travail d'une transformation isobare : W = -P·ΔV.",
      "Pour un gaz parfait en transformation quelconque : ΔU = nCvΔT.",
    ],
    schemas: [
      `Transformations thermodynamiques :\n\nIsotherme  : T = cste → ΔU = 0 (GP)\nIsobare    : P = cste → W = -PΔV, Q = nCpΔT\nIsochore   : V = cste → W = 0, ΔU = Q\nAdiabatique: Q = 0   → ΔU = W\n\nConvention de signe :\n  W > 0 : travail REÇU par le système\n  Q > 0 : chaleur REÇUE par le système`,
    ],
    tips: [
      "Bien noter la convention de signe : W et Q > 0 si reçus par le système.",
      "Pour un gaz parfait : ΔU ne dépend que de ΔT. Pour une transformation isotherme : ΔU = 0.",
      "À pression constante : ΔH = Qp. L'enthalpie est très utile en chimie.",
    ],
    remember: [
      "ΔU = W + Q : conservation de l'énergie (1er principe). W et Q algébriques.",
      "Gaz parfait : ΔU = nCvΔT (pour toute transformation, quelle que soit P ou V).",
      "Transformation adiabatique : Q = 0. Isotherme (GP) : ΔU = 0.",
    ],
  },
  {
    id: 12,
    title: "Ondes mécaniques",
    icon: "🌊",
    color: "#a78bfa",
    definition: "Une onde mécanique est une perturbation qui se propage dans un milieu matériel sans transport de matière, mais avec transport d'énergie. Elle peut être transversale (corde) ou longitudinale (son).",
    formulas: [
      { name: "Célérité d'une onde", expr: "v = λ × f = λ/T", desc: "v (m/s), λ (m), f (Hz), T (s)" },
      { name: "Relation période-fréquence", expr: "T = 1/f", desc: "T (s), f (Hz)" },
      { name: "Retard temporel", expr: "τ = d/v", desc: "d : distance de propagation" },
      { name: "Déphasage", expr: "φ = 2πd/λ = 2πτ/T", desc: "φ en radians" },
      { name: "Équation d'onde", expr: "y(x,t) = A·cos(2πft - 2πx/λ)", desc: "" },
    ],
    demonstrations: [
      "Démonstration du retard entre deux capteurs : τ = d/v → mesure de la célérité.",
      "Calcul du déphasage entre deux points : φ = 2πd/λ.",
      "Condition de synchro : φ = 2kπ (en phase) ; φ = (2k+1)π (en opposition de phase).",
    ],
    schemas: [
      `Onde progressive sinusoïdale :\n\n  y\n  ↑ A        λ\n  | /\\      /\\\n  |/  \\    /  \\\n  +----\\--/----\\------→ x\n  |     \\/      \\/\n  | -A\n\nDans le temps : T = période\nDans l'espace : λ = longueur d'onde\nCélérité : v = λ/T = λ·f`,
    ],
    tips: [
      "Vitesse du son dans l'air ≈ 340 m/s ; dans l'eau ≈ 1500 m/s ; dans les solides > 5000 m/s.",
      "Pour mesurer v : placer deux capteurs à distance d connue, mesurer le retard τ → v = d/τ.",
      "Attention : l'onde transporte de l'ÉNERGIE, pas de la matière.",
    ],
    remember: [
      "v = λf est la relation fondamentale. Connaître les unités par cœur.",
      "Retard τ = d/v. Déphasage φ = 2πd/λ = 2πτ/T.",
      "Onde transversale : vibration ⊥ propagation. Longitudinale : vibration ∥ propagation (son).",
    ],
  },
  {
    id: 13,
    title: "Interférences et diffraction",
    icon: "🔬",
    color: "#34d399",
    definition: "La diffraction est l'étalement d'une onde au passage d'une ouverture ou d'un obstacle. Les interférences résultent de la superposition de deux ondes cohérentes pouvant se renforcer (constructives) ou s'annuler (destructives).",
    formulas: [
      { name: "Angle de diffraction", expr: "sin θ ≈ θ = λ/a", desc: "a : largeur de la fente, λ : longueur d'onde" },
      { name: "Largeur de la tache centrale", expr: "L = 2Dλ/a", desc: "D : distance fente-écran" },
      { name: "Interfranges (Young)", expr: "i = λD/d", desc: "d : distance inter-fentes, D : distance fentes-écran" },
      { name: "Interférences constructives", expr: "δ = kλ (k ∈ ℤ)", desc: "δ : différence de marche" },
      { name: "Interférences destructives", expr: "δ = (k + ½)λ", desc: "" },
      { name: "Différence de marche", expr: "δ = d × sinθ ≈ d × y/D", desc: "Pour θ petit" },
    ],
    demonstrations: [
      "Calcul de l'interfrange dans l'expérience des fentes de Young : δ = d·y/D → franges brillantes si δ = kλ → y_k = kλD/d → i = λD/d.",
      "Relation entre l'angle de diffraction et les paramètres : θ = λ/a (critère de Rayleigh).",
    ],
    schemas: [
      `Fentes de Young :\n\n  S₁ ●──────────────────● écran\n  d↕                      franges\n  S₂ ●\n     |←────── D ─────────→|\n\nBrillant : δ = kλ → y_k = kλD/d\nSombre  : δ = (k+½)λ\nInterfrange i = λD/d\n\nDiffraction (fente fine) :\n  θ = λ/a → tache ∝ 1/a`,
    ],
    tips: [
      "Interféromètre de Young : plus D est grand ou d est petit → plus les franges sont espacées.",
      "Lumière blanche : franges colorées, frange centrale blanche.",
      "Diffraction : fente plus étroite → tache plus large (λ/a augmente).",
    ],
    remember: [
      "Interférences constructives : δ = kλ (en phase). Destructives : δ = (k+½)λ.",
      "Interfrange de Young : i = λD/d.",
      "Diffraction : θ = λ/a. Plus la fente est étroite, plus la diffraction est importante.",
    ],
  },
  {
    id: 14,
    title: "Lunette astronomique",
    icon: "🔭",
    color: "#fbbf24",
    definition: "La lunette astronomique est un instrument d'optique grossissant composé d'un objectif (lentille convergente de grande focale) et d'un oculaire (lentille convergente de courte focale). Elle forme une image à l'infini d'objets lointains.",
    formulas: [
      { name: "Grossissement", expr: "G = -f'_obj / f'_oc = angle_image / angle_objet", desc: "Réglage afocal" },
      { name: "Longueur de la lunette (afocale)", expr: "L = f'_obj + f'_oc", desc: "Image intermédiaire au foyer objet de l'oculaire" },
      { name: "Vergence", expr: "V = 1/f' (dioptries)", desc: "f' en mètres" },
      { name: "Relation conjugaison (lentille mince)", expr: "1/OA' - 1/OA = 1/f'", desc: "O : centre optique" },
      { name: "Grandissement transversal", expr: "γ = OA'/OA = A'B'/AB", desc: "" },
    ],
    demonstrations: [
      "Construction géométrique de l'image donnée par l'objectif, puis par l'oculaire.",
      "Calcul du grossissement G en réglage afocal : G = f'_obj/f'_oc (valeur absolue).",
      "Condition afocale : l'image de l'objectif se forme au foyer objet de l'oculaire.",
    ],
    schemas: [
      `Lunette astronomique (réglage afocal) :\n\n  Objectif    F'_obj=F_oc  Oculaire\n  (f'_obj)      ↕         (f'_oc)\n  ───────────────────────────────\n  ←──f'_obj──→←──f'_oc──→\n  ←───────── L ──────────→\n\nObjet à l'∞ → Image intermédiaire en F'_obj\nImage intermédiaire en F_oc → Image finale à l'∞\nGrossissement : G = -f'_obj / f'_oc`,
    ],
    tips: [
      "Réglage afocal = réglage standard pour un observateur emmétrope (vision normale).",
      "L'objectif a une grande focale (collecte la lumière), l'oculaire une petite focale (grossit).",
      "Lunette terrestre = lunette astronomique + lentille de redressement (image droite).",
    ],
    remember: [
      "Grossissement G = f'_obj / f'_oc (en valeur absolue, réglage afocal).",
      "Réglage afocal : F'_objectif coïncide avec F_oculaire.",
      "Plus la focale de l'oculaire est petite → grossissement plus grand.",
    ],
  },
  {
    id: 15,
    title: "Modèle du photon - Effet photoélectrique",
    icon: "💡",
    color: "#38bdf8",
    definition: "Le modèle corpusculaire de la lumière décrit le photon comme un quantum d'énergie. L'effet photoélectrique (émission d'électrons par un métal éclairé) ne s'explique que par ce modèle et a valu le prix Nobel à Einstein en 1921.",
    formulas: [
      { name: "Énergie d'un photon", expr: "E = h × f = hc/λ", desc: "h = 6,626×10⁻³⁴ J·s, c = 3×10⁸ m/s" },
      { name: "Effet photoélectrique", expr: "E_c_max = hf - W_s", desc: "W_s : travail de sortie du métal (J)" },
      { name: "Fréquence seuil", expr: "f_s = W_s / h", desc: "Effet photoélectrique si f ≥ f_s" },
      { name: "Longueur d'onde seuil", expr: "λ_s = hc / W_s", desc: "Effet photoélectrique si λ ≤ λ_s" },
      { name: "Tension d'arrêt", expr: "eU_a = E_c_max = hf - W_s", desc: "e = 1,6×10⁻¹⁹ C" },
    ],
    demonstrations: [
      "Explication de l'effet photoélectrique : un photon cède son énergie hf à un électron. Si hf > Ws, l'électron est émis.",
      "L'effet ne dépend pas de l'intensité lumineuse mais de la fréquence (modèle ondulatoire en échec).",
      "Calcul de la tension d'arrêt : eUₐ = hf - Ws → mesure de h.",
    ],
    schemas: [
      `Effet photoélectrique :\n\n    Photon hf\n       ↓\n  ─────────────────  ← métal (W_s)\n     ●→→→→→→→       électron émis\n          E_c = hf - W_s\n\nCondition : hf ≥ W_s  (f ≥ f_s)\n\nSi hf < W_s : aucun électron émis\n(même avec une intensité lumineuse forte)`,
    ],
    tips: [
      "Convertir W_s en eV ↔ J : 1 eV = 1,6×10⁻¹⁹ J.",
      "Graphe Ec_max = f(f) : droite de pente h, ordonnée à l'origine = -Ws.",
      "La fréquence seuil est une propriété du matériau, pas de la lumière.",
    ],
    remember: [
      "E_photon = hf = hc/λ. La constante de Planck h = 6,626×10⁻³⁴ J·s.",
      "Effet photoélectrique : hf ≥ Ws pour émettre un électron.",
      "Ec_max = hf - Ws : l'énergie cinétique maximale des électrons émis.",
    ],
  },
  {
    id: 16,
    title: "Circuit RC - Dynamique d'un système électrique",
    icon: "🔌",
    color: "#a78bfa",
    definition: "Un circuit RC (résistance + condensateur) est un système du premier ordre dont la charge/décharge suit une loi exponentielle. La constante de temps τ = RC caractérise la rapidité du phénomène.",
    formulas: [
      { name: "Constante de temps", expr: "τ = R × C", desc: "R (Ω), C (F), τ (s)" },
      { name: "Charge du condensateur", expr: "u_C(t) = E(1 - e^(-t/τ))", desc: "E : tension d'alimentation" },
      { name: "Décharge du condensateur", expr: "u_C(t) = U₀ × e^(-t/τ)", desc: "U₀ : tension initiale" },
      { name: "Courant de charge", expr: "i(t) = (E/R) × e^(-t/τ)", desc: "" },
      { name: "Équation différentielle", expr: "RC × du_C/dt + u_C = E", desc: "Loi des mailles" },
      { name: "Énergie stockée", expr: "E_C = ½ × C × u_C²", desc: "En joules" },
    ],
    demonstrations: [
      "Établissement de l'équation différentielle par la loi des mailles : E = u_R + u_C = Ri + u_C.",
      "Résolution : u_C(t) = E(1 - e^(-t/τ)) avec τ = RC (vérification par substitution).",
      "À t = τ : u_C = E(1 - 1/e) ≈ 0,63E. À t = 5τ : régime permanent (≈ 99%).",
    ],
    schemas: [
      `Circuit RC (charge) :\n\n   E ──────┬─────────┐\n           R         C\n           ├────────┤\n           │  u_C   │\n   GND ────┴─────────┘\n\nu_C(t)\n  E ─────────────────  (asymptote)\n  |         ___----\n0,63E|─ ─ ─/\n  |       /\n  |      /\n  +──────+──────────→ t\n         τ   5τ`,
    ],
    tips: [
      "Tangente à l'origine : intersecte l'asymptote en t = τ. Méthode graphique pour lire τ.",
      "Condensateur chargé = interrupteur ouvert en régime permanent.",
      "Condensateur déchargé = court-circuit en début de charge (t = 0).",
    ],
    remember: [
      "τ = RC : constante de temps, en secondes si R en Ω et C en F.",
      "À t = τ : 63% de la charge finale. À t = 5τ : état permanent (99%).",
      "L'équation différentielle RC·du/dt + u = E est à connaître par cœur.",
    ],
  },
  {
    id: 17,
    title: "Transferts quantiques d'énergie",
    icon: "⚛️",
    color: "#f472b6",
    definition: "Dans le modèle atomique de Bohr, les électrons occupent des niveaux d'énergie quantifiés. Les transitions entre niveaux s'accompagnent d'absorption ou d'émission de photons d'énergie bien définie.",
    formulas: [
      { name: "Énergie du photon émis/absorbé", expr: "hf = |E_f - E_i|", desc: "E_f et E_i : énergies des niveaux (eV ou J)" },
      { name: "Niveaux d'énergie (H)", expr: "E_n = -13,6 / n² eV", desc: "n : nombre quantique principal" },
      { name: "Conversion eV↔J", expr: "1 eV = 1,6 × 10⁻¹⁹ J", desc: "" },
      { name: "Énergie d'ionisation", expr: "E_ion = -E_1 = 13,6 eV", desc: "Pour l'hydrogène" },
      { name: "Longueur d'onde émise", expr: "λ = hc / (E_f - E_i)", desc: "Transition n_i → n_f (n_i > n_f pour émission)" },
    ],
    demonstrations: [
      "Calcul de la longueur d'onde émise lors d'une transition : λ = hc/ΔE.",
      "Série de Balmer (visible) : transitions vers n=2. Série de Lyman (UV) : transitions vers n=1.",
      "Calcul de l'énergie d'ionisation : passage de E_1 à E=0.",
    ],
    schemas: [
      `Niveaux d'énergie de l'hydrogène :\n\n  E (eV)\n   0 ─────────────────  n=∞ (ionisé)\n  -0,85 ───────────────  n=4\n  -1,51 ───────────────  n=3 ─→ Balmer\n  -3,40 ───────────────  n=2 ─→ Lyman\n              ↑ photon\n -13,6 ───────────────  n=1 (fondamental)\n\nÉmission : n_i → n_f (n_i > n_f)\nAbsorption : n_f → n_i (n_i > n_f)`,
    ],
    tips: [
      "En émission : l'atome passe d'un niveau supérieur à un niveau inférieur. Photon émis.",
      "En absorption : l'atome absorbe un photon et passe à un niveau supérieur.",
      "Série de Balmer : transitions vers n=2, émettent dans le visible.",
    ],
    remember: [
      "hf = ΔE = |E_i - E_f| pour tout transfert quantique d'énergie.",
      "Niveaux de l'H : E_n = -13,6/n² eV. Fondamental n=1 à -13,6 eV.",
      "1 eV = 1,6×10⁻¹⁹ J. Conversion OBLIGATOIRE avant calcul en SI.",
    ],
  },
  {
    id: 18,
    title: "Analyse spectrale",
    icon: "🌈",
    color: "#34d399",
    definition: "L'analyse spectrale étudie la lumière émise ou absorbée par les substances pour en déduire leur composition chimique. Chaque élément possède un spectre caractéristique (raies spectrales) qui constitue sa « signature ».",
    formulas: [
      { name: "Relation couleur-longueur d'onde", expr: "400 nm (violet) → 800 nm (rouge)", desc: "Visible : 400-800 nm" },
      { name: "Relation f et λ", expr: "c = λ × f", desc: "c = 3×10⁸ m/s" },
      { name: "Loi de Wien", expr: "λ_max × T = 2,898 × 10⁻³ m·K", desc: "Corps noir : T en K" },
      { name: "Loi de Beer-Lambert", expr: "A = ε × l × C", desc: "A : absorbance, ε : coefficient molaire, l (cm), C (mol/L)" },
    ],
    demonstrations: [
      "Application de la loi de Beer-Lambert pour dosage par spectrophotométrie : A = f(C) est une droite.",
      "Utilisation d'un spectre d'émission pour identifier un élément chimique.",
      "Calcul de la longueur d'onde de la raie d'un atome à partir des niveaux d'énergie.",
    ],
    schemas: [
      `Types de spectres :\n\n  Spectre continu : ══════════════════\n  (lampe à incandescence)  ROYGBIV\n\n  Spectre d'émission : ──│──────│──│──\n  (atome excité)        raies brillantes\n\n  Spectre d'absorption : ══│══════│══│══\n  (lumière blanche – atomes froids)\n                          raies sombres\n\n→ Les raies d'absorption correspondent\n  aux raies d'émission du même élément`,
    ],
    tips: [
      "Courbe d'étalonnage (Beer-Lambert) : tracer A = f(C) → droite passant par l'origine si A < 1.",
      "Longueur d'onde d'analyse : choisir le maximum d'absorption (λmax) pour plus de sensibilité.",
      "Spectre solaire (Fraunhofer) : spectre d'absorption → identifie les éléments dans l'atmosphère solaire.",
    ],
    remember: [
      "Chaque élément a un spectre de raies unique : c'est sa signature spectrale.",
      "Beer-Lambert : A = εlC → dosage colorimétrique par spectrophotométrie.",
      "Spectre d'émission = raies brillantes sur fond sombre. Absorption = raies sombres sur fond continu.",
    ],
  },
  {
    id: 19,
    title: "Méthodes physiques d'analyse",
    icon: "🔍",
    color: "#fbbf24",
    definition: "Les méthodes physiques d'analyse permettent d'identifier et de doser des composés chimiques. Les principales méthodes au programme sont la spectroscopie IR, la RMN ¹H et la chromatographie.",
    formulas: [
      { name: "Déplacement chimique (RMN)", expr: "δ (ppm) = (ν_obs - ν_ref) / ν_spectrométre × 10⁶", desc: "TMS comme référence (δ = 0 ppm)" },
      { name: "Rf (chromatographie)", expr: "Rf = d_composé / d_éluant", desc: "0 < Rf < 1" },
      { name: "Nombre d'onde (IR)", expr: "σ = 1/λ (en cm⁻¹)", desc: "σ(C=O) ≈ 1700 cm⁻¹, σ(O-H) ≈ 3300 cm⁻¹" },
    ],
    demonstrations: [
      "Identification d'un groupe fonctionnel par IR : lecture du tableau des bandes caractéristiques.",
      "Déduction de la structure par RMN : multiplicité, intégration et déplacement chimique.",
      "CCM : séparation de mélanges, identification par comparaison des Rf avec des témoins.",
    ],
    schemas: [
      `Spectroscopie IR - Bandes clés :\n\n  σ (cm⁻¹) | Liaison | Groupe\n  ─────────────────────────────\n  3200-3600 | O-H     | alcool, acide\n  2500-3300 | O-H     | acide carboxylique\n  2850-2960 | C-H     | alcane\n  1700-1750 | C=O     | cétone, aldéhyde, ester\n  1600-1680 | C=C     | alcène\n  1000-1200 | C-O     | alcool, ester\n\nRMN ¹H - Déplacements typiques :\n  TMS (0) | R-CH₃ (0-1) | R-CH₂-R (1-2)\n  C=C-H (4-6) | Ar-H (6-9) | COOH (10-12)`,
    ],
    tips: [
      "IR : bande large ≈ 3300 cm⁻¹ → O-H (alcool ou acide). Bande fine ≈ 1700 cm⁻¹ → C=O.",
      "RMN : règle N+1 pour la multiplicité (doublet = voisin 1H, triplet = 2H voisins).",
      "CCM : Rf identique = même composé. Toujours comparer avec des témoins connus.",
    ],
    remember: [
      "IR : identifier les groupes fonctionnels par les bandes d'absorption caractéristiques.",
      "RMN ¹H : déplacement δ (ppm), multiplicité (n+1), intégration (nb de H).",
      "Rf = d_composé/d_solvant (CCM). Plus Rf est grand → moins le composé est polaire.",
    ],
  },
  {
    id: 20,
    title: "Utilisation de Python pour la modélisation",
    icon: "🐍",
    color: "#38bdf8",
    definition: "Python est utilisé en physique-chimie pour modéliser des phénomènes physiques, résoudre des équations différentielles numériquement et analyser des données expérimentales.",
    formulas: [
      { name: "Méthode d'Euler", expr: "y(t+h) = y(t) + h × f(t, y(t))", desc: "h : pas de temps, f : fonction dérivée" },
      { name: "Régression linéaire (numpy)", expr: "np.polyfit(x, y, 1)", desc: "Retourne [pente, ordonnée origine]" },
      { name: "Tableau numpy", expr: "np.linspace(a, b, n)", desc: "n points entre a et b" },
    ],
    demonstrations: [
      "Résolution numérique de l'équation du mouvement (PFD) par la méthode d'Euler.",
      "Tracé de la courbe v(t) à partir de a(t) en intégrant numériquement.",
      "Régression linéaire sur des données expérimentales pour déterminer une constante physique.",
    ],
    schemas: [
      `Algorithme d'Euler (chute libre) :\n\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ng = 9.81; h = 0.01\nt = [0]; y = [0]; v = [0]\n\nfor i in range(1000):\n    a = -g\n    v.append(v[-1] + h * a)\n    y.append(y[-1] + h * v[-1])\n    t.append(t[-1] + h)\n\nplt.plot(t, y)\nplt.xlabel('t (s)'); plt.ylabel('y (m)')\nplt.show()`,
    ],
    tips: [
      "Plus le pas h est petit → plus la simulation est précise (mais plus lente).",
      "Toujours tracer les résultats avec matplotlib pour vérifier la cohérence physique.",
      "Utiliser scipy.integrate.odeint pour une intégration plus précise des EDO.",
    ],
    remember: [
      "Méthode d'Euler : approximation de la dérivée par un taux d'accroissement fini.",
      "numpy pour les calculs numériques, matplotlib pour les graphiques, scipy pour les méthodes avancées.",
      "Validation : comparer la simulation à la solution analytique quand elle existe.",
    ],
  },
];