export const chapters = [
  {
    id: 1,
    title: "Constitution de la matière - La mole",
    icon: "⚛️",
    color: "#38bdf8",
    definition: "La chimie quantitative s'appuie sur le concept de mole : une unité de comptage des entités chimiques (atomes, molécules, ions). La constitution de la matière décrit comment atomes et molécules s'assemblent, se comptent et se transforment. Maîtrise absolue requise : ces formules servent dans TOUS les autres chapitres de chimie.",
    formulas: [
      { name: "Nombre de moles (masse)", expr: "n = m / M", desc: "n (mol), m (g), M (g/mol)" },
      { name: "Nombre de moles (concentration)", expr: "n = C × V", desc: "C (mol/L), V en LITRES obligatoire" },
      { name: "Nombre d'entités", expr: "N = n × Nₐ", desc: "Nₐ = 6,022 × 10²³ mol⁻¹" },
      { name: "Concentration molaire", expr: "C = n / V = m / (M × V)", desc: "C (mol/L)" },
      { name: "Concentration massique", expr: "Cm = m / V  |  Cm = C × M", desc: "Cm (g/L) ; C = Cm / M" },
      { name: "Pourcentage massique", expr: "w% = (m_soluté / m_solution) × 100", desc: "" },
      { name: "C depuis w% et densité d", expr: "C = (w% × d × 1000) / (M × 100)", desc: "Exercice classique concours !" },
      { name: "Dilution", expr: "C₁V₁ = C₂V₂", desc: "Conservation des moles de soluté" },
    ],
    demonstrations: [
      "Établissement de n = m/M depuis la définition de la masse molaire (M = masse d'une mole).",
      "Calcul du nombre d'entités : N = (m/M) × Nₐ. Ex : 36 g de glucose (M=180) → n = 0,2 mol → N = 1,2×10²³.",
      "Loi de dilution : n₁ = n₂ → C₁V₁ = C₂V₂. Conservation des moles lors de la dilution.",
      "Calcul de C depuis w% et densité d : m_solution/1L = d×1000 g → m_soluté = w%/100 × m_sol → C = m_soluté/M.",
    ],
    schemas: [
      `Tableau d'avancement :\n\nÉquation :  aA + bB → cC + dD\nÉtat init. : n(A)₀   n(B)₀     0    0\nÉtat x    : n(A)₀-ax  n(B)₀-bx   cx   dx\nÉtat final : n(A)f    n(B)f    n(C)f  n(D)f\n\nRéactif limitant : celui pour qui n(X)/coeff est le plus petit\nxmax = min(nₐ/a ; n_B/b)`,
      `Tableau des grandeurs :\n\n  Symbole | Grandeur            | Unité\n  ────────────────────────────────────\n  n       | Quantité de matière | mol\n  m       | Masse               | g\n  M       | Masse molaire       | g/mol\n  C       | Concentration mol.  | mol/L\n  Cm      | Concentration mass. | g/L\n  V       | Volume de solution  | L  ← TOUJOURS en L !`,
    ],
    tips: [
      "PIÈGE N°1 : toujours convertir mL en L avant tout calcul (250 mL → 0,250 L).",
      "Pour w% avec densité : partir de 1 litre de solution → masse totale = d × 1000 g → m_soluté = w%/100 × m_tot → n = m_soluté/M → C = n/1L. Ex : HCl 37%, d=1,19, M=36,5 → C = 12 mol/L.",
      "Ne pas confondre Cm (g/L) et C (mol/L) : les relier via M → Cm = C × M.",
      "Tableau d'avancement : toujours identifier le RÉACTIF LIMITANT (celui qui donne le plus petit xmax).",
    ],
    remember: [
      "Les 3 formules de base : n = m/M ; n = C×V ; N = n×Nₐ (Nₐ = 6,022×10²³).",
      "Dilution : C₁V₁ = C₂V₂. Les moles de soluté se conservent.",
      "Tableau d'avancement : réactif limitant → celui pour qui n/coeff stœchio est minimal.",
    ],
    extras: [
      {
        title: "Méthode : Réactif limitant",
        content: "Pour aA + bB → produits, calculer xmax(A) = n(A)/a et xmax(B) = n(B)/b. Le réactif limitant est celui qui donne le PLUS PETIT xmax. Le xmax global est ce plus petit xmax.",
      },
      {
        title: "Méthode : Taux d'avancement",
        content: "τ = xf / xmax × 100 (%). τ = 100% → réaction totale. τ < 100% → réaction limitée (équilibre). τ faible → réaction très défavorable thermodynamiquement.",
      },
      {
        title: "Exemple numérique (concours)",
        content: "CH₄ + 2O₂ → CO₂ + 2H₂O avec 3 mol CH₄ et 4 mol O₂ :\nxmax(CH₄) = 3/1 = 3 mol | xmax(O₂) = 4/2 = 2 mol → xmax = 2 mol, O₂ limitant\nÉtat final : CH₄ = 1 mol (excès), O₂ = 0, CO₂ = 2 mol, H₂O = 4 mol",
      },
    ],
  },
  {
    id: 2,
    title: "Suivi temporel - Cinétique chimique",
    icon: "⏱️",
    color: "#a78bfa",
    definition: "La cinétique chimique étudie la vitesse à laquelle se déroulent les réactions chimiques. Elle permet de suivre l'évolution d'un système au cours du temps et d'identifier les facteurs qui influencent cette vitesse (température, concentration, catalyseur).",
    formulas: [
      { name: "Vitesse volumique de réaction", expr: "v = (1/V) × (dx/dt)", desc: "x : avancement (mol), V : volume (L)" },
      { name: "Vitesse en concentration", expr: "v = d[P]/dt = −d[R]/dt", desc: "Pour les coefficients stœchio = 1" },
      { name: "Temps de demi-réaction", expr: "t₁/₂ : [A](t₁/₂) = [A]₀/2", desc: "Lecture graphique ou calcul" },
      { name: "Loi de vitesse (ordre 1)", expr: "[A](t) = [A]₀ × e^(−kt)", desc: "k : constante de vitesse (s⁻¹)" },
      { name: "Loi d'Arrhénius", expr: "k = A × e^(−Eₐ/RT)", desc: "Eₐ : énergie d'activation, R = 8,314 J/mol/K" },
    ],
    demonstrations: [
      "Détermination graphique de la vitesse instantanée : tangente à la courbe [P](t) ou [R](t). La pente de la tangente donne la vitesse en ce point.",
      "Détermination du t₁/₂ : sur le graphe [R](t), lire la date t pour laquelle [R] = [R]₀/2.",
      "Influence de la température sur k via la loi d'Arrhénius : ln(k) = −Eₐ/RT + ln(A) → si ln(k) = f(1/T) est une droite de pente −Eₐ/R.",
    ],
    schemas: [
      `Courbe cinétique :\n\n[Réactif]\n   |\n[A]₀ |\\  \n     | \\ \n[A]₀/2|--+------\n     |    \\    \n     |     \\___\n     +--+-------→ t\n           t₁/₂\n\nVitesse instantanée = pente de la tangente\nVitesse initiale = pente de la tangente en t=0 (maximale)`,
    ],
    tips: [
      "La tangente en t=0 donne la vitesse initiale (maximale). En t quelconque, tracer la tangente à la courbe en ce point.",
      "Pour identifier l'ordre : si t₁/₂ est constant quelque soit [A]₀ → ordre 1. Si t₁/₂ ∝ 1/[A]₀ → ordre 2.",
      "Facteurs cinétiques : T ↑ → k ↑ → réaction plus rapide. Catalyseur → abaisse Eₐ → k ↑ sans changer l'équilibre.",
      "Ne pas confondre vitesse de réaction (cinétique) et état d'équilibre (thermodynamique) : une réaction peut être rapide ET défavorable.",
    ],
    remember: [
      "La vitesse de réaction est toujours positive et diminue au cours du temps.",
      "Le temps de demi-réaction t₁/₂ est lu sur le graphe : quand [R] = [R]₀/2.",
      "Facteurs cinétiques : température ↑ → vitesse ↑ ; catalyseur → abaisse Eₐ.",
    ],
    extras: [],
  },
  {
    id: 3,
    title: "Équilibres chimiques - Acide/Base",
    icon: "⚖️",
    color: "#34d399",
    definition: "Un équilibre chimique est un état dynamique où les vitesses des réactions directe et inverse sont égales. En chimie acido-basique (Brønsted), un acide donne H⁺ et une base accepte H⁺. Chapitre incontournable : sort à CHAQUE concours.",
    formulas: [
      { name: "pH", expr: "pH = −log[H₃O⁺]  |  [H₃O⁺] = 10^(−pH)", desc: "" },
      { name: "Produit ionique de l'eau", expr: "Ke = [H₃O⁺][OH⁻] = 10⁻¹⁴", desc: "À 25°C, pKe = 14" },
      { name: "Constante d'acidité", expr: "Ka = [A⁻][H₃O⁺] / [HA]", desc: "Pour HA + H₂O ⇌ A⁻ + H₃O⁺" },
      { name: "pKa", expr: "pKa = −log(Ka)  |  Ka = 10^(−pKa)", desc: "" },
      { name: "Acide fort Cₐ", expr: "pH = −log(Cₐ)", desc: "Dissociation totale" },
      { name: "Base forte Cb", expr: "pH = 14 + log(Cb)", desc: "Dissociation totale" },
      { name: "Acide faible Cₐ, pKa", expr: "pH = ½(pKa − log Cₐ)", desc: "Approximation valable si α << 1" },
      { name: "Base faible Cb, pKa", expr: "pH = 7 + ½(pKa + log Cb)", desc: "" },
      { name: "Solution tampon (Henderson)", expr: "pH = pKa + log([A⁻]/[AH])", desc: "Mélange acide faible + base conjuguée" },
      { name: "Mi-titrage acide faible", expr: "pH = pKa", desc: "Quand V_ajouté = Véq/2" },
      { name: "Taux d'avancement", expr: "τ = xf / xmax", desc: "Réaction totale si τ = 1" },
    ],
    demonstrations: [
      "Démonstration de pH = −log(Ca) pour un acide fort (ex: HCl totalement dissocié → [H₃O⁺] = Ca).",
      "Calcul du pH d'un acide faible : tableau d'avancement → Ka = x²/(Ca−x) → si x << Ca : x = √(Ka×Ca) → pH = ½(pKa − log Ca).",
      "Titrage pH-métrique : à l'équivalence Cₐ×Vₐ = Cb×Véq. Point équivalent par méthode des tangentes parallèles.",
      "À mi-titrage d'un acide faible : n(A⁻) = n(HA) → rapport = 1 → log(1) = 0 → pH = pKa.",
    ],
    schemas: [
      `Diagramme de prédominance :\n\n  HA prédominante   |   A⁻ prédominante\n                    |\n  ←── pH < pKa ────pKa──── pH > pKa ──→\n                    |\n              [HA] = [A⁻]`,
      `Titrage acide fort / base forte :\n\n  pH\n  14 │                    ────────\n     │                  /\n   7 │─ ─ ─ ─ ─ ─ ─X─ ─\n     │            /\n   1 │ ──────────\n     └─────────────────────→ V(NaOH)\n              Véq\n\nAcide faible + base forte : X > 7 à l'équivalence`,
      `Les 4 formules de pH - Résumé :\n\n┌─────────────────────────────────────────────┐\n│  Acide fort  :  pH = −log(Ca)              │\n│  Base forte  :  pH = 14 + log(Cb)          │\n│  Acide faible:  pH = ½(pKa − log Ca)       │\n│  Base faible :  pH = 7 + ½(pKa + log Cb)  │\n│  Tampon      :  pH = pKa + log([A⁻]/[HA]) │\n└─────────────────────────────────────────────┘`,
    ],
    tips: [
      "PIÈGE : pH d'un acide FAIBLE ≠ −log(Ca). Utiliser la formule avec pKa : pH = ½(pKa − log Ca).",
      "PIÈGE : pH à l'équivalence acide faible + base forte EST > 7 (pas 7 !). Milieu basique car A⁻ est une base.",
      "Toujours sommer les volumes pour les concentrations après ajout du titrant : V_total = Vₐ + Vajouté.",
      "Solution tampon : résiste aux variations de pH. Efficace quand [A⁻]/[HA] est entre 0,1 et 10, soit pH ≈ pKa ± 1.",
    ],
    remember: [
      "Acide = donneur H⁺ / Base = accepteur H⁺ (Brønsted). Écrire le couple acide/base conjugué.",
      "pH = pKa ↔ [HA] = [A⁻] : mi-titrage d'un acide faible, point remarquable.",
      "Ke = 10⁻¹⁴ à 25°C. pH<7 acide, pH>7 basique. Titrage: Cₐ×Vₐ = Cb×Véq à l'équivalence.",
    ],
    extras: [
      {
        title: "Titrage conductimétrique (complément)",
        content: "Principe : mesure de la conductance G en fonction du volume ajouté. Courbe = droites qui se croisent au point équivalent (pas une courbe en S).\n\nAcide fort + base forte : σ diminue avant Véq (H₃O⁺ très mobile disparaît), puis augmente (excès HO⁻).\nAcide faible + base forte : σ augmente légèrement avant Véq, puis vite après.\n\nConductivités molaires ioniques : H₃O⁺ (35,0) >> HO⁻ (19,8) >> K⁺ (7,4) > Cl⁻ (7,6) > Na⁺ (5,0) > CH₃COO⁻ (4,1) [mS·m²/mol]",
      },
    ],
  },
  {
    id: 4,
    title: "Stratégies en synthèse organique",
    icon: "🧪",
    color: "#f472b6",
    definition: "La synthèse organique construit des molécules par transformations chimiques contrôlées. Elle requiert de choisir réactions (substitution, addition, élimination, oxydation/réduction), conditions opératoires, et méthodes de purification/identification. La connaissance des mécanismes réactionnels (nucléophile/électrophile, flèches courbes) est essentielle.",
    formulas: [
      { name: "Rendement", expr: "η = n_obtenu / n_théorique × 100%", desc: "n en moles" },
      { name: "Réaction de substitution (SN)", expr: "R-X + Nu⁻ → R-Nu + X⁻", desc: "Nu : nucléophile, X : groupe partant" },
      { name: "Addition électrophile (AE)", expr: "alcène + E⁺ → carbocation → produit", desc: "Règle de Markovnikov" },
      { name: "Élimination (E2)", expr: "R-CHX-CH₂-R + base → R-CH=CH-R + HX", desc: "Base forte encombrée + chaleur" },
      { name: "Rf (CCM)", expr: "Rf = d_composé / d_front_solvant", desc: "0 < Rf < 1" },
    ],
    demonstrations: [
      "Règle de Markovnikov : en addition HX sur alcène asymétrique, H se fixe sur le C le plus H-substitué (le carbocation le plus stable se forme).",
      "Distinction SN vs E : nucléophile fort + C primaire → SN2 préféré ; base encombrée + C tertiaire → E2 préféré.",
      "Calcul du rendement : η = m_obtenu / (n_théorique × M_produit) × 100%.",
    ],
    schemas: [
      `Étapes d'une synthèse :\n\n  Matières premières\n         ↓\n   [Réaction] → Solvant, T°, catalyseur\n         ↓\n   Produit brut (mélange)\n         ↓\n   [Purification] → Filtration, distillation,\n                     recristallisation, extraction\n         ↓\n   Produit pur → [Identification] → IR, RMN, CCM`,
      `Mécanismes réactionnels :\n\nNucléophile (Nu:) : donneur de doublet, riche en e⁻\n  → H₂O, NH₃, HO⁻, Cl⁻, CN⁻\nÉlectrophile (E⁺) : accepteur de doublet, pauvre en e⁻\n  → H⁺, C portant δ+, BF₃, AlCl₃\n\nRègle d'or : Nu: attaque E⁺\nFlèche courbe : part du doublet (riche), arrive sur l'atome pauvre\n\nSN2 : Nu attaque C par derrière → inversion de configuration\nSN1 : formation d'un carbocation, puis attaque Nu (2 étapes)`,
    ],
    tips: [
      "CCM : Rf identique à un témoin = même composé. Révélation : UV ou réactif chimique.",
      "Mécanismes : une flèche courbe représente le déplacement d'UN DOUBLET (2 e⁻). Elle part toujours de là où il Y A des électrons vers là où ils VONT.",
      "Pour choisir la réaction : identifier d'abord le groupe fonctionnel du réactif ET du produit cible. La différence indique le type de transformation.",
      "Rendement < 100% toujours en pratique : pertes lors des étapes de purification, réactions secondaires.",
    ],
    remember: [
      "Identifier la transformation : addition, substitution, élimination, oxydation ou réduction.",
      "Purification obligatoire : CCM, distillation ou recristallisation selon l'état physique.",
      "Identification : IR (groupes fonctionnels), RMN ¹H (environnement des H). Comparer avec spectre de référence.",
    ],
    extras: [
      {
        title: "Mécanismes réactionnels - Flèches courbes",
        content: "Flèche à double tête (⟶) : déplacement d'un doublet (2 électrons).\nFlèche à tête simple (⇀) : déplacement d'un électron seul (radical).\n\nAttaque nucléophile : Nu: → C⁺ (flèche part du doublet de Nu, arrive sur C⁺)\nRupture hétérolytique : C–X → C⁺ + :X⁻ (flèche part de la liaison C–X, arrive sur X)\n\nIntermédiaires réactionnels :\n- Carbocation R⁺ : stable si tertiaire > secondaire > primaire\n- Carbanion R⁻ : peu stable en général\n- Radical R• : électron non apparié",
      },
    ],
  },
  {
    id: 5,
    title: "Description d'un mouvement",
    icon: "🏃",
    color: "#fbbf24",
    definition: "La cinématique décrit le mouvement sans s'intéresser à ses causes. Elle définit la position, la vitesse et l'accélération d'un objet dans un référentiel donné. Toujours préciser le référentiel (terrestre, héliocentrique...) et le repère (cartésien, polaire...).",
    formulas: [
      { name: "Vecteur position", expr: "OM⃗ = x(t)⃗i + y(t)⃗j", desc: "En 2D dans un repère cartésien" },
      { name: "Vecteur vitesse", expr: "v⃗ = dOM⃗/dt", desc: "vx = dx/dt, vy = dy/dt" },
      { name: "Norme de la vitesse", expr: "|v⃗| = √(vx² + vy²)", desc: "En m/s" },
      { name: "Vecteur accélération", expr: "a⃗ = dv⃗/dt", desc: "ax = dvx/dt, ay = dvy/dt" },
      { name: "MRU (accélération nulle)", expr: "x(t) = x₀ + v₀t", desc: "v = cste" },
      { name: "MRUA (accélération constante)", expr: "x(t) = x₀ + v₀t + ½at²", desc: "v(t) = v₀ + at" },
      { name: "MCU (circulaire uniforme)", expr: "a_n = v²/R  (centripète)", desc: "|v| = cste, direction change" },
    ],
    demonstrations: [
      "Passage de la courbe x(t) à v(t) par dérivation graphique : vx = pente de la tangente à x(t).",
      "Détermination d'une trajectoire : écrire x(t) et y(t), exprimer t depuis x(t), substituer dans y(t) pour obtenir y = f(x).",
      "Accélération centripète en MCU : a⃗ dirigée vers le centre, |a| = v²/R = ω²R.",
    ],
    schemas: [
      `Types de mouvements :\n\nMRU  : a = 0, v = cste       → x(t) droite, traj. rectiligne\nMRUA : a = cste ≠ 0          → v(t) droite, x(t) parabole\nMCU  : |v| = cste, a⊥v       → trajectoire circulaire\n\nVecteur accélération (décomposition) :\n  ┌─ aₜ (tangentielle) : variation de |v|\na = │\n  └─ aₙ (normale)      : variation de direction, → centre`,
    ],
    tips: [
      "La pente de v(t) donne l'accélération scalaire. La pente de x(t) (MRU) ou la tangente donne la vitesse.",
      "Pour la trajectoire parabolique : écrire x(t) et y(t), puis t = x/(v₀cosθ), substituer dans y(t).",
      "Toujours préciser le référentiel et le repère. Poser l'origine clairement.",
    ],
    remember: [
      "v⃗ = dOM⃗/dt et a⃗ = dv⃗/dt : dérivation par rapport au temps.",
      "MRU : vitesse constante, pas d'accélération. MRUA : accélération constante.",
      "La trajectoire est l'équation y = f(x) obtenue en éliminant le paramètre t.",
    ],
    extras: [],
  },
  {
    id: 6,
    title: "Deuxième loi de Newton",
    icon: "🍎",
    color: "#38bdf8",
    definition: "La deuxième loi de Newton (Principe Fondamental de la Dynamique, PFD) relie la somme des forces extérieures à l'accélération du centre de masse. Elle est valable dans un référentiel galiléen. C'est le cœur de la mécanique classique.",
    formulas: [
      { name: "PFD (2ème loi de Newton)", expr: "ΣF⃗ext = m × a⃗", desc: "m (kg), a⃗ (m/s²), dans un référentiel galiléen" },
      { name: "Poids", expr: "P⃗ = m × g⃗", desc: "g ≈ 9,81 m/s² orienté vers le bas" },
      { name: "Réaction normale", expr: "N⃗ ⊥ surface, orientée surface→objet", desc: "" },
      { name: "Force de frottement", expr: "f ≤ μ × N", desc: "μ : coefficient de frottement" },
      { name: "Tension d'un fil", expr: "T⃗ : dans la direction du fil, vers le fil", desc: "Fil tendu et inextensible" },
      { name: "Projection sur axe x", expr: "m·ax = ΣFx", desc: "Une équation par axe" },
    ],
    demonstrations: [
      "Plan incliné : projection du PFD sur l'axe x (∥ plan) et y (⊥ plan). Axe x : ma = P sinα − f. Axe y : 0 = N − P cosα.",
      "Système de deux solides liés (Atwood) : PFD pour chaque solide, puis on additionne pour trouver a, on isole pour les tensions.",
      "Équation différentielle de l'oscillateur : k·x + m·d²x/dt² = 0 → oscillations sinusoïdales.",
    ],
    schemas: [
      `Plan incliné :\n\n     y ↑  N↑\n       \\  |\n        \\ |\n  f ←──● ← P sinα (projeté)\n        |↘\n        |  P⃗ (poids)\n  ──────────────\n      α\n\nAxe x (∥ plan, sens du mouvement) :\n  m·a = P sinα − f = mg sinα − μmg cosα\nAxe y (⊥ plan) :\n  0 = N − P cosα  →  N = mg cosα`,
    ],
    tips: [
      "Toujours faire un schéma des forces (diagramme de corps libre) AVANT d'écrire le PFD.",
      "Choisir intelligemment les axes : un axe parallèle au mouvement réduit les calculs.",
      "En équilibre : ΣF⃗ = 0⃗. PFD est la généralisation : si a = 0 → équilibre ET si a ≠ 0 → mouvement accéléré.",
    ],
    remember: [
      "ΣF⃗ext = ma⃗ : toujours dans un référentiel galiléen, appliqué au centre de masse.",
      "Projeter sur les axes : on obtient autant d'équations scalaires que d'axes.",
      "Si accélération nulle → immobile ou MRU (1ère loi de Newton).",
    ],
    extras: [],
  },
  {
    id: 7,
    title: "Mouvement dans un champ de pesanteur",
    icon: "🪂",
    color: "#a78bfa",
    definition: "Dans un champ de pesanteur uniforme, la seule force exercée sur un projectile est son poids (frottements négligés). Ce mouvement est la superposition d'un MRU horizontal et d'un MRUA vertical (chute libre). La trajectoire est une parabole.",
    formulas: [
      { name: "Équations horaires (lancer oblique)", expr: "x(t) = v₀cosθ·t\ny(t) = v₀sinθ·t − ½gt²", desc: "Lancé en (0,0) à v₀ et angle θ" },
      { name: "Composantes de vitesse", expr: "vx(t) = v₀cosθ (cste)\nvy(t) = v₀sinθ − gt", desc: "" },
      { name: "Équation de trajectoire", expr: "y = x·tanθ − gx²/(2v₀²cos²θ)", desc: "Parabole" },
      { name: "Hauteur maximale", expr: "hmax = v₀²sin²θ / (2g)", desc: "Quand vy = 0" },
      { name: "Portée", expr: "xmax = v₀²sin(2θ) / g", desc: "Maximale pour θ = 45°" },
      { name: "Chute libre verticale", expr: "y(t) = h − ½gt²  →  t_chute = √(2h/g)", desc: "Lancer vertical depuis h" },
    ],
    demonstrations: [
      "Preuve que la trajectoire est une parabole : t = x/(v₀cosθ) → substituer dans y(t) → y = x tanθ − gx²/(2v₀²cos²θ).",
      "Calcul de la portée : y(t_chute) = 0 → t_chute = 2v₀sinθ/g → x_portée = v₀cosθ × t_chute = v₀²sin(2θ)/g.",
      "Portée maximale pour θ = 45° : d(xmax)/dθ = 0 → cos(2θ) = 0 → 2θ = 90° → θ = 45°.",
    ],
    schemas: [
      `Lancer oblique :\n\n  y\n  ↑         ●  ← sommet (vy=0)\n  |        / \\\n  |       /   \\\n  |      /     \\\n  |  θ  /       \\\n  | ←→ /         \\\n  +---●-----------●-→ x\n    v₀              portée\n\n  Horizontalement : MRU (vx = cste)\n  Verticalement   : MRUA (ay = −g)`,
    ],
    tips: [
      "Lancer horizontal (θ=0°) : x = v₀t et y = −½gt². Trajectoire : y = −gx²/(2v₀²).",
      "Chute libre (θ=90°, v₀=0) : y = −½gt². Temps de chute depuis h : t = √(2h/g).",
      "Symétrie : angle θ et angle (90°−θ) donnent la même portée sur sol horizontal.",
    ],
    remember: [
      "Horizontalement : MRU (vx constant). Verticalement : MRUA (accélération = −g).",
      "Trajectoire = parabole (sauf lancer vertical = droite).",
      "Portée max pour θ = 45° uniquement si sol horizontal et départ au même niveau.",
    ],
    extras: [],
  },
  {
    id: 8,
    title: "Mouvement dans un champ électrostatique uniforme",
    icon: "⚡",
    color: "#f472b6",
    definition: "Dans un champ électrique uniforme E⃗ (condensateur plan), une particule chargée subit F⃗ = qE⃗. Le mouvement est rigoureusement analogue au projectile dans la pesanteur : MRU perpendiculaire au champ et MRUA parallèle au champ.",
    formulas: [
      { name: "Force électrique", expr: "F⃗ = q × E⃗", desc: "q (C), E (V/m = N/C)" },
      { name: "Champ entre plaques (condensateur)", expr: "E = U_AB / d", desc: "U (V), d : distance inter-plaques (m)" },
      { name: "Accélération de la particule", expr: "a = qE/m  (selon l'axe du champ)", desc: "" },
      { name: "Équations horaires (entrée horizontale à v₀)", expr: "x(t) = v₀t\ny(t) = ½(qE/m)t²", desc: "Champ selon Oy" },
      { name: "Déviation transversale", expr: "y = qE·x² / (2mv₀²)", desc: "Équation de la parabole" },
      { name: "Énergie cinétique gagnée (accélération)", expr: "ΔEc = q × Uacc = ½mv² − ½mv₀²", desc: "Théorème énergie-travail" },
      { name: "Déviation en sortie des plaques", expr: "y_sortie = qEL² / (2mv₀²)", desc: "L : longueur des plaques" },
    ],
    demonstrations: [
      "Trajectoire parabolique : PFD → ay = qE/m, ax = 0 → x = v₀t, y = ½(qE/m)t² → éliminer t → y = qEx²/(2mv₀²).",
      "Déviation y_sortie = qEL²/(2mv₀²) avec L = longueur des plaques et t_sortie = L/v₀.",
      "Théorème énergie-travail entre plaques accélératrices : W = qUacc → ΔEc = qUacc.",
    ],
    schemas: [
      `Condensateur plan (déflexion) :\n\n  + + + + + + + + +\n  ─────────────────\n  → → → ●→→→→→→→\n  v₀     ↓ F=qE (q>0, E↓)\n  ─────────────────\n  − − − − − − − − −\n  |←──── L ──────→|\n\nÉlectron (q<0) : dévié VERS la plaque +\nIon positif (q>0) : dévié VERS la plaque −\nAnalogue au lancer horizontal dans g`,
    ],
    tips: [
      "Analogie TOTALE avec le projectile : g ↔ qE/m, poids ↔ force électrique.",
      "Si la charge est négative (électron : q = −e), la force est OPPOSÉE au champ E⃗.",
      "Ne pas oublier que r = R_planète + altitude pour les satellites (analogie avec ce chapitre).",
    ],
    remember: [
      "F⃗ = qE⃗ : parallèle au champ pour q>0, antiparallèle pour q<0 (électron).",
      "E = U/d pour un condensateur plan.",
      "Mouvement : MRU ⊥ champ, MRUA ∥ champ. Trajectoire parabolique.",
    ],
    extras: [],
  },
  {
    id: 9,
    title: "Mouvement des satellites - Lois de Kepler",
    icon: "🛸",
    color: "#34d399",
    definition: "Les lois de Kepler (empiriques, 1609-1619) décrivent le mouvement des planètes. Newton les unifie avec la gravitation universelle (1687). Ces lois permettent de calculer vitesses, périodes et altitudes orbitales pour tout corps en orbite.",
    formulas: [
      { name: "Gravitation universelle (Newton)", expr: "F = G × m₁m₂ / r²", desc: "G = 6,674×10⁻¹¹ N·m²/kg²" },
      { name: "3ème loi de Kepler", expr: "T² / a³ = 4π² / (GM)", desc: "M = masse corps central, a = demi-grand axe" },
      { name: "Vitesse orbitale circulaire", expr: "v = √(GM/r)", desc: "r = rayon de l'orbite circulaire" },
      { name: "Période orbitale circulaire", expr: "T = 2πr / v = 2π√(r³/GM)", desc: "" },
      { name: "Force centripète = Force gravitationnelle", expr: "mv²/r = GMm/r²", desc: "Condition d'orbite circulaire" },
      { name: "Vitesse de libération", expr: "v_lib = √(2GM/R)", desc: "R = rayon de la planète" },
      { name: "Énergie mécanique orbitale", expr: "Em = −GMm / (2r)", desc: "Orbite circulaire, négative (liée)" },
    ],
    demonstrations: [
      "Démonstration de T²/r³ = 4π²/(GM) : PFD appliqué au satellite → F_grav = F_centripète → GMm/r² = m(2πr/T)²/r → T² = 4π²r³/(GM).",
      "Vitesse orbitale : GMm/r² = mv²/r → v² = GM/r → v = √(GM/r).",
      "Satellite géostationnaire : T = 24h = 86 400 s → r³ = GMT²/(4π²) → r ≈ 42 164 km → altitude h = r − R_Terre ≈ 35 786 km.",
    ],
    schemas: [
      `3 lois de Kepler :\n\n1ère loi : Les orbites sont des ELLIPSES\n   dont le Soleil occupe UN foyer.\n\n         *           *\n      *               *\n    *    ●Foyer  ●    *\n      *               *\n         *           *\n\n2ème loi : Loi des AIRES\n   Aires balayées en temps égaux sont égales.\n   (vitesse orbitale ↑ au périhélie)\n\n3ème loi : T²/a³ = K = constante\n   (même constante pour tous les corps\n    orbitant autour du même astre central)`,
    ],
    tips: [
      "Satellite géostationnaire : T = 24h = 86 400 s. Orbite circulaire équatoriale. Altitude ≈ 36 000 km.",
      "La 3ème loi de Kepler permet de comparer deux orbites sans connaître G ni M : T₁²/a₁³ = T₂²/a₂³.",
      "r dans les formules = RAYON DE L'ORBITE = R_planète + altitude. Ne jamais confondre avec le rayon de la planète !",
    ],
    remember: [
      "3 lois de Kepler : orbites elliptiques / loi des aires / T²/a³ = constante.",
      "Orbite circulaire : v = √(GM/r) et T² = 4π²r³/(GM).",
      "Satellite géostationnaire : T = 24h, orbite équatoriale, r ≈ 42 000 km depuis le centre Terre.",
    ],
    extras: [],
  },
  {
    id: 10,
    title: "Description d'un système thermodynamique - Gaz parfait",
    icon: "🌡️",
    color: "#fbbf24",
    definition: "La thermodynamique décrit les échanges d'énergie dans les systèmes macroscopiques. Le modèle du gaz parfait suppose des molécules ponctuelles sans interactions mutuelles. Il décrit bien les gaz réels à basse pression et haute température.",
    formulas: [
      { name: "Équation d'état des gaz parfaits", expr: "PV = nRT", desc: "R = 8,314 J/(mol·K), T en Kelvin OBLIGATOIRE" },
      { name: "Conversion température", expr: "T(K) = θ(°C) + 273,15", desc: "" },
      { name: "Loi de Boyle-Mariotte (isotherme)", expr: "P₁V₁ = P₂V₂", desc: "T et n constants" },
      { name: "Loi de Gay-Lussac (isochore)", expr: "P₁/T₁ = P₂/T₂", desc: "V et n constants" },
      { name: "Loi de Charles (isobare)", expr: "V₁/T₁ = V₂/T₂", desc: "P et n constants" },
      { name: "Loi générale (deux variables changent)", expr: "P₁V₁/T₁ = P₂V₂/T₂ = nR", desc: "n constant" },
      { name: "Volume molaire (CNTP)", expr: "Vm = RT/P = 22,4 L/mol à 0°C, 1 atm", desc: "" },
      { name: "Énergie interne gaz parfait", expr: "U = (3/2)nRT (monoatomique)", desc: "Ne dépend que de T" },
    ],
    demonstrations: [
      "Dérivation des lois de Boyle, Gay-Lussac et Charles depuis PV = nRT en fixant une variable.",
      "Volume molaire à CNTP (T=273 K, P=101 325 Pa) : Vm = RT/P = 8,314×273/101325 = 0,0224 m³ = 22,4 L/mol.",
      "L'énergie interne d'un gaz parfait ne dépend que de T : U = U(T) uniquement (théorème de Joule).",
    ],
    schemas: [
      `Diagramme PV (isothermes) :\n\n  P\n  ↑  T₃ > T₂ > T₁\n  | \\  (PV = nRT = cste pour chaque courbe)\n  |  ─\\T₃\n  |    ─\\T₂\n  |      ─\\T₁\n  +──────────→ V\n\nP↑ quand T↑ (à V constant) → Gay-Lussac\nV↑ quand T↑ (à P constant) → Charles\nPV cste quand T cste (isotherme) → Boyle`,
    ],
    tips: [
      "OBLIGATOIRE : toujours convertir en Kelvin avant tout calcul ! T = 25°C → T = 298 K.",
      "CNTP : T = 273,15 K (0°C), P = 101 325 Pa (1 atm) → Vm = 22,4 L/mol.",
      "Si deux variables changent simultanément : utiliser P₁V₁/T₁ = P₂V₂/T₂ (n constant).",
    ],
    remember: [
      "PV = nRT : loi fondamentale. R = 8,314 J/(mol·K). T TOUJOURS en Kelvin.",
      "Gaz parfait : pas d'interactions entre molécules. U dépend uniquement de T.",
      "3 lois dérivées : Boyle (T=cste), Gay-Lussac (V=cste), Charles (P=cste).",
    ],
    extras: [],
  },
  {
    id: 11,
    title: "Bilans d'énergie - Premier principe",
    icon: "🔥",
    color: "#38bdf8",
    definition: "Le premier principe de la thermodynamique est la loi de conservation de l'énergie : la variation d'énergie interne d'un système est égale à la somme du travail et de la chaleur reçus. C'est une loi universelle.",
    formulas: [
      { name: "Premier principe", expr: "ΔU = W + Q", desc: "W et Q > 0 si REÇUS par le système" },
      { name: "Travail forces de pression (isobare)", expr: "W = −P_ext × ΔV", desc: "ΔV = V_final − V_initial" },
      { name: "Capacité thermique massique", expr: "Q = m × c × ΔT", desc: "c (J/kg/K) ou (J/g/K)" },
      { name: "Capacité molaire à P constant", expr: "Q = n × Cp × ΔT", desc: "Cp (J/mol/K)" },
      { name: "Capacité molaire à V constant", expr: "ΔU = n × Cv × ΔT", desc: "Gaz parfait : Cp − Cv = R" },
      { name: "Enthalpie", expr: "H = U + PV  →  ΔH = Qp", desc: "Chaleur échangée à pression constante" },
      { name: "Transformation isotherme (GP)", expr: "ΔU = 0  →  W = −Q", desc: "Gaz parfait, T constante" },
      { name: "Transformation adiabatique", expr: "Q = 0  →  ΔU = W", desc: "" },
    ],
    demonstrations: [
      "Transformation adiabatique (Q=0) : ΔU = W. Si W>0 (compression) → T augmente.",
      "Transformation isochore (V=cste) : W = −P·ΔV = 0 → ΔU = Q. Toute l'énergie reçue augmente U.",
      "Pour un gaz parfait en toute transformation : ΔU = nCvΔT (car U ne dépend que de T).",
    ],
    schemas: [
      `Résumé des 4 transformations :\n\n┌──────────────┬──────────┬───────────┬──────────┐\n│ Type         │ Condition│ W         │ Q        │\n├──────────────┼──────────┼───────────┼──────────┤\n│ Isotherme(GP)│ T = cste │ W = −Q    │ Q = −W   │\n│ Isobare      │ P = cste │ −PΔV      │ nCpΔT    │\n│ Isochore     │ V = cste │ W = 0     │ ΔU = Q   │\n│ Adiabatique  │ Q = 0    │ ΔU = W    │ Q = 0    │\n└──────────────┴──────────┴───────────┴──────────┘\n\nConvention : W>0 et Q>0 si REÇUS par le système`,
    ],
    tips: [
      "Convention de signe CRUCIALE : W et Q sont positifs si le système les REÇOIT.",
      "Gaz parfait : ΔU = nCvΔT pour TOUTE transformation (même isobare). Car U(T) uniquement.",
      "ΔH = Qp : l'enthalpie est la chaleur échangée à pression constante (très utile en chimie).",
    ],
    remember: [
      "ΔU = W + Q : 1er principe, conservation de l'énergie.",
      "Gaz parfait : ΔU = nCvΔT et Cp − Cv = R.",
      "Isotherme (GP) : ΔU=0. Isochore : W=0. Adiabatique : Q=0.",
    ],
    extras: [],
  },
  {
    id: 12,
    title: "Ondes mécaniques",
    icon: "🌊",
    color: "#a78bfa",
    definition: "Une onde mécanique est une perturbation qui se propage dans un milieu matériel sans transport de matière, mais avec transport d'énergie. Elle peut être transversale (vibration ⊥ propagation : corde) ou longitudinale (vibration ∥ propagation : son).",
    formulas: [
      { name: "Relation fondamentale", expr: "v = λ × f = λ/T", desc: "v (m/s), λ (m), f (Hz), T (s)" },
      { name: "Relation période-fréquence", expr: "T = 1/f", desc: "" },
      { name: "Retard temporel", expr: "τ = d/v", desc: "d : distance de propagation (m)" },
      { name: "Déphasage", expr: "φ = 2πd/λ = 2πτ/T", desc: "φ en radians" },
      { name: "En phase", expr: "φ = 2kπ  (k entier)", desc: "" },
      { name: "En opposition de phase", expr: "φ = (2k+1)π", desc: "" },
      { name: "Équation d'onde sinusoïdale", expr: "y(x,t) = A·cos(2πft − 2πx/λ)", desc: "" },
    ],
    demonstrations: [
      "Mesure de la célérité : placer deux capteurs à distance d connue, mesurer le retard τ → v = d/τ.",
      "Déphasage entre deux points : φ = 2πd/λ. En phase si d = kλ. En opposition si d = (k+½)λ.",
    ],
    schemas: [
      `Onde progressive sinusoïdale :\n\n  y\n  ↑ A        λ (longueur d'onde)\n  | /\\      /\\\n  |/  \\    /  \\\n  +----\\--/----\\------→ x\n  |     \\/      \\/ \n  |-A\n\nDans le TEMPS  : T = 1/f (période)\nDans l'ESPACE  : λ = longueur d'onde\nCélérité       : v = λ/T = λ·f\n\nCélérités typiques :\n  Son dans l'air  : ≈ 340 m/s\n  Son dans l'eau  : ≈ 1500 m/s\n  Lumière (vide)  : c = 3×10⁸ m/s`,
    ],
    tips: [
      "v = λf est la relation fondamentale. Bien connaître les unités pour ne pas faire d'erreur.",
      "Pour mesurer v expérimentalement : v = d/τ avec deux capteurs à distance d connue.",
      "Onde TRANSPORTE de l'énergie, pas de la matière (les grains de sable sous une vague ne se déplacent pas horizontalement).",
    ],
    remember: [
      "v = λf : relation fondamentale. T = 1/f.",
      "Retard τ = d/v. Déphasage φ = 2πd/λ.",
      "Transversale : vibration ⊥ propagation. Longitudinale : vibration ∥ propagation (son).",
    ],
    extras: [],
  },
  {
    id: 13,
    title: "Interférences et diffraction",
    icon: "🔬",
    color: "#34d399",
    definition: "La diffraction est l'étalement d'une onde au passage d'une ouverture (fente). Les interférences résultent de la superposition de deux ondes cohérentes : elles peuvent se renforcer (constructives) ou s'annuler (destructives). Ces phénomènes prouvent la nature ondulatoire de la lumière.",
    formulas: [
      { name: "Angle de diffraction (fente unique)", expr: "sin θ ≈ θ = λ/a", desc: "a : largeur de la fente" },
      { name: "Largeur tache centrale (diffraction)", expr: "L = 2Dλ/a", desc: "D : distance fente-écran" },
      { name: "Interfranges (fentes de Young)", expr: "i = λD/d", desc: "d : distance entre fentes, D : distance fentes-écran" },
      { name: "Interférences constructives (franges brillantes)", expr: "δ = kλ  (k ∈ ℤ)", desc: "δ : différence de marche" },
      { name: "Interférences destructives (franges sombres)", expr: "δ = (k + ½)λ", desc: "" },
      { name: "Différence de marche", expr: "δ ≈ d × y / D", desc: "Pour petits angles (d << D)" },
      { name: "Position des franges brillantes", expr: "y_k = kλD/d", desc: "k = 0 : frange centrale" },
    ],
    demonstrations: [
      "Interfrange de Young : fringe brillante en y_k si δ = kλ → d·y_k/D = kλ → y_k = kλD/d → i = y_{k+1} − y_k = λD/d.",
      "Diffraction : θ = λ/a → tache plus large si a plus petite ou λ plus grande.",
    ],
    schemas: [
      `Fentes de Young (double fente) :\n\n  Source      Fentes       Écran\n     ●        S₁ ●\n              d ↕         I (intensité)\n              S₂ ●         │ \\  | \\  | \\\n                           │   \\|   |/\n  |←── D₁ ──→|←── D₂ ──→|\n\nBrillant : δ = kλ → y_k = kλD/d\nSombre   : δ = (k+½)λ\nInterfrange : i = λD/d\n\nDiffraction (fente simple) :\n  θ = λ/a (angle du premier minimum)\n  Tache ∝ 1/a (plus étroite → plus diffracte)`,
    ],
    tips: [
      "Plus D est grand ou d est petit → franges plus espacées (i = λD/d).",
      "Lumière blanche : franges colorées (irisées), frange centrale BLANCHE (δ = 0 pour toutes λ).",
      "Diffraction plus visible si λ ≈ a. Si a >> λ : pas de diffraction notable (optique géométrique).",
    ],
    remember: [
      "Interférences constructives : δ = kλ. Destructives : δ = (k+½)λ.",
      "Interfrange de Young : i = λD/d. Plus d est petit, plus i est grand.",
      "Diffraction : θ = λ/a. Fente plus étroite → étalement plus grand.",
    ],
    extras: [],
  },
  {
    id: 14,
    title: "Lunette astronomique",
    icon: "🔭",
    color: "#fbbf24",
    definition: "La lunette astronomique est un instrument d'optique convergent formé d'un objectif (grande focale) et d'un oculaire (petite focale). En réglage afocal, un objet à l'infini donne une image à l'infini, et le grossissement est G = f'_obj/f'_oc.",
    formulas: [
      { name: "Grossissement (réglage afocal)", expr: "G = f'_obj / f'_oc = α' / α", desc: "α : angle objet, α' : angle image" },
      { name: "Longueur de la lunette (afocale)", expr: "L = f'_obj + f'_oc", desc: "F'_obj coïncide avec F_oc" },
      { name: "Vergence d'une lentille", expr: "V = 1/f'  (dioptries, δ)", desc: "f' en MÈTRES" },
      { name: "Relation de conjugaison", expr: "1/OA' − 1/OA = 1/f'", desc: "O : centre optique, distances algébriques" },
      { name: "Grandissement transversal", expr: "γ = OA'/OA = A'B'/AB", desc: "" },
    ],
    demonstrations: [
      "Construction géométrique en réglage afocal : rayon ∥ à l'axe → F'_obj (image intermédiaire = objet pour l'oculaire en F_oc) → sort ∥ à l'axe → image à l'infini.",
      "Calcul du grossissement : G = α'/α = (f'_obj/f'_oc) en utilisant les propriétés des rayons focaux.",
    ],
    schemas: [
      `Lunette astronomique — réglage afocal :\n\n Objectif(f'_obj)    F'=F_oc   Oculaire(f'_oc)\n  ────│────────────────●────────────│────\n       ←──── f'_obj ──→←── f'_oc ──→\n       ←─────────── L = f'_obj + f'_oc ──→\n\nObjet à l'∞ → 2 rayons :\n  1) Rayon ∥ axe → passe par F'_obj\n  2) Rayon par le centre optique de l'objectif → non dévié\n\nImage intermédiaire en F'_obj ≡ F_oc\nImage finale à l'∞ (observateur emmétrope)\nGrossissement G = f'_obj / f'_oc`,
    ],
    tips: [
      "Réglage afocal = pour un observateur emmétrope (vision normale, non accomodé).",
      "Objectif : grande focale (collecte max de lumière). Oculaire : petite focale (grossit l'image).",
      "Pour augmenter le grossissement : prendre un oculaire de focale plus petite.",
    ],
    remember: [
      "G = f'_obj / f'_oc (réglage afocal).",
      "Condition afocale : F'_objectif = F_oculaire.",
      "L = f'_obj + f'_oc = longueur de la lunette.",
    ],
    extras: [],
  },
  {
    id: 15,
    title: "Modèle du photon - Effet photoélectrique",
    icon: "💡",
    color: "#38bdf8",
    definition: "Le modèle corpusculaire décrit la lumière comme un flux de photons, chacun portant une énergie quantifiée E = hf. L'effet photoélectrique (émission d'électrons par un métal éclairé) ne s'explique QUE par ce modèle (Einstein, 1905, Nobel 1921). Il met en échec le modèle ondulatoire.",
    formulas: [
      { name: "Énergie d'un photon", expr: "E = h × f = hc/λ", desc: "h = 6,626×10⁻³⁴ J·s, c = 3×10⁸ m/s" },
      { name: "Effet photoélectrique", expr: "Ec_max = hf − Ws", desc: "Ws : travail de sortie du métal (J)" },
      { name: "Condition d'émission", expr: "hf ≥ Ws  ↔  f ≥ fs  ↔  λ ≤ λs", desc: "" },
      { name: "Fréquence seuil", expr: "fs = Ws / h", desc: "Propriété du matériau" },
      { name: "Longueur d'onde seuil", expr: "λs = hc / Ws", desc: "" },
      { name: "Tension d'arrêt", expr: "eUa = Ec_max = hf − Ws", desc: "e = 1,6×10⁻¹⁹ C" },
      { name: "Conversion eV ↔ J", expr: "1 eV = 1,6×10⁻¹⁹ J", desc: "" },
    ],
    demonstrations: [
      "Explication de l'effet photoélectrique : 1 photon donne son énergie hf à 1 électron. Si hf ≥ Ws → électron émis avec Ec_max = hf − Ws.",
      "Pourquoi le modèle ondulatoire échoue : avec les ondes, augmenter l'intensité devrait suffire. Or expérimentalement : si f < fs, AUCUN électron émis quelle que soit l'intensité → preuve que l'énergie est quantifiée.",
      "Mesure de h : graphe Ec_max = f(f) → droite de pente h, ordonnée à l'origine = −Ws.",
    ],
    schemas: [
      `Effet photoélectrique :\n\n    Photon hf (f ≥ fs)\n           ↓\n  ─────────────────────  ← métal (Ws)\n       ●─→→→→→→→→       électron émis\n           Ec_max = hf − Ws\n\nSi f < fs : aucun électron (même forte intensité)\nSi f ≥ fs : émission immédiate (même faible intensité)\n\nCourbe Ec_max = f(fréquence) :\n     Ec │          /  pente = h\n        │        /\n      0 │──────/────→ f\n        │ ← fs\n  −Ws   │/`,
    ],
    tips: [
      "Convertir Ws en eV ↔ J : si Ws = 4 eV → Ws = 4 × 1,6×10⁻¹⁹ = 6,4×10⁻¹⁹ J.",
      "La fréquence seuil est une propriété intrinsèque du matériau (lié à sa structure électronique).",
      "Graphe Ec_max = f(f) : pente = h (constante de Planck) → méthode expérimentale pour mesurer h.",
    ],
    remember: [
      "E_photon = hf = hc/λ. h = 6,626×10⁻³⁴ J·s.",
      "Effet photoélectrique : hf ≥ Ws pour émettre. Ec_max = hf − Ws.",
      "1 photon → 1 électron. L'intensité change le nombre de photons, pas leur énergie.",
    ],
    extras: [],
  },
  {
    id: 16,
    title: "Circuit RC - Dynamique d'un système électrique",
    icon: "🔌",
    color: "#a78bfa",
    definition: "Un circuit RC (résistance R + condensateur C) est un système du premier ordre. La charge/décharge suit une loi exponentielle caractérisée par la constante de temps τ = RC. C'est la base de l'électronique analogique.",
    formulas: [
      { name: "Constante de temps", expr: "τ = R × C", desc: "R (Ω), C (F) → τ (s)" },
      { name: "Charge du condensateur", expr: "u_C(t) = E(1 − e^(−t/τ))", desc: "E : tension d'alimentation" },
      { name: "Décharge du condensateur", expr: "u_C(t) = U₀ × e^(−t/τ)", desc: "U₀ : tension initiale" },
      { name: "Courant (charge)", expr: "i(t) = (E/R) × e^(−t/τ)", desc: "i = C × du_C/dt" },
      { name: "Équation différentielle (loi des mailles)", expr: "RC × du_C/dt + u_C = E", desc: "" },
      { name: "Énergie stockée dans C", expr: "E_C = ½ × C × u_C²", desc: "En joules" },
      { name: "Valeurs clés", expr: "t=τ : u_C = 0,63E  |  t=5τ : u_C ≈ E (99%)", desc: "" },
    ],
    demonstrations: [
      "Établissement de l'équation différentielle par la loi des mailles : E = u_R + u_C = R·i + u_C = RC·du_C/dt + u_C.",
      "Résolution : solution générale u_C(t) = E + A·e^(−t/τ). Condition initiale u_C(0) = 0 → A = −E → u_C(t) = E(1−e^(−t/τ)).",
      "Vérification : à t=τ → u_C = E(1−1/e) = E×0,632 ≈ 0,63E. À t=5τ → e^(−5) ≈ 0,007 → u_C ≈ 0,993E ≈ E.",
    ],
    schemas: [
      `Circuit RC :\n\n   E ─────┬───R───┬\n          │       C\n          │       │  u_C(t)\n   GND ───┴───────┘\n\nu_C(t) pendant la charge :\n  E ────────────────── (asymptote)\n  |         __------\n0,63E|─ ─ ─/\n  |       /  ← tangente à l'origine\n  |      /    intersecte E en t = τ\n  +──────+──────────→ t\n         τ    5τ\n\nu_C(t) pendant la décharge :\n  U₀|\\  \n     | \\\n0,37U₀|─ \\\n     |   \\──\n     +────+──────→ t\n          τ`,
    ],
    tips: [
      "Méthode graphique pour lire τ : la tangente à la courbe en t=0 intersecte l'asymptote horizontale en t = τ.",
      "Condensateur en régime permanent (t >> 5τ) : se comporte comme un INTERRUPTEUR OUVERT (i = 0).",
      "Condensateur en t = 0 (si initialement déchargé) : se comporte comme un COURT-CIRCUIT (u_C = 0).",
    ],
    remember: [
      "τ = RC en secondes (R en Ω, C en F).",
      "À t = τ : u_C = 63% de la valeur finale. À t = 5τ : régime permanent (99%).",
      "Équation différentielle : RC·du/dt + u = E. À connaître et savoir établir.",
    ],
    extras: [],
  },
  {
    id: 17,
    title: "Transferts quantiques d'énergie",
    icon: "⚛️",
    color: "#f472b6",
    definition: "Dans le modèle atomique de Bohr (1913), les électrons occupent des niveaux d'énergie discrets (quantifiés). Les transitions entre niveaux s'accompagnent d'émission ou d'absorption de photons d'énergie précise hf = |ΔE|.",
    formulas: [
      { name: "Énergie du photon émis/absorbé", expr: "hf = |Ef − Ei|  ↔  λ = hc / |ΔE|", desc: "" },
      { name: "Niveaux d'énergie de l'hydrogène", expr: "En = −13,6 / n² (eV)", desc: "n = 1, 2, 3,... (entier)" },
      { name: "Niveau fondamental", expr: "E₁ = −13,6 eV  (n=1)", desc: "État le plus stable" },
      { name: "Énergie d'ionisation", expr: "E_ion = −E₁ = 13,6 eV", desc: "Pour arracher l'électron" },
      { name: "Conversion eV ↔ J", expr: "1 eV = 1,6×10⁻¹⁹ J", desc: "OBLIGATOIRE en SI" },
    ],
    demonstrations: [
      "Émission : atome passe de n_i → n_f avec n_i > n_f → photon émis d'énergie hf = E_{n_i} − E_{n_f}.",
      "Absorption : atome absorbe un photon hf → passe de n_f → n_i avec n_i > n_f.",
      "Séries spectrales H : Lyman (n_f=1, UV), Balmer (n_f=2, visible), Paschen (n_f=3, IR).",
    ],
    schemas: [
      `Niveaux d'énergie de l'hydrogène :\n\n  E (eV)\n   0 ──────────────────  n=∞ (ionisé)\n  −0,85 ────────────────  n=4\n  −1,51 ────────────────  n=3  ─╮\n  −3,40 ────────────────  n=2  ─╯→ Série de Balmer (VISIBLE)\n              ↑ photon\n −13,6 ────────────────  n=1 (fondamental)\n                              ↑ Série de Lyman (UV)\n\nÉmission  : n_i → n_f  (n_i > n_f) → photon émis\nAbsorption: n_f → n_i  (n_i > n_f) → photon absorbé`,
    ],
    tips: [
      "Balmer (visible) : transitions vers n=2. Longueurs d'onde dans 400-700 nm.",
      "Toujours convertir les énergies en Joules pour utiliser hf = ΔE : ΔE(J) = ΔE(eV) × 1,6×10⁻¹⁹.",
      "Plus le niveau est élevé (n grand), plus l'énergie est proche de 0 (moins liée).",
    ],
    remember: [
      "hf = |ΔE| pour tout transfert quantique. λ = hc/|ΔE|.",
      "Niveaux H : En = −13,6/n² eV. Fondamental : n=1, E₁ = −13,6 eV.",
      "1 eV = 1,6×10⁻¹⁹ J : conversion OBLIGATOIRE avant tout calcul.",
    ],
    extras: [],
  },
  {
    id: 18,
    title: "Analyse spectrale",
    icon: "🌈",
    color: "#34d399",
    definition: "L'analyse spectrale étudie la lumière émise ou absorbée par les substances pour en déduire leur composition. Chaque élément possède un spectre de raies unique (sa « signature »). La loi de Beer-Lambert permet le dosage par spectrophotométrie.",
    formulas: [
      { name: "Spectre visible", expr: "400 nm (violet) → 700 nm (rouge)", desc: "UV < 400 nm ; IR > 700 nm" },
      { name: "Relation f et λ", expr: "c = λ × f", desc: "c = 3×10⁸ m/s" },
      { name: "Loi de Wien (corps noir)", expr: "λ_max × T = 2,898×10⁻³ m·K", desc: "T en Kelvin" },
      { name: "Loi de Beer-Lambert", expr: "A = ε × l × C", desc: "A : absorbance, ε (L/mol/cm), l (cm), C (mol/L)" },
      { name: "Absorbance", expr: "A = log(I₀/I) = −log(T)", desc: "T = I/I₀ : transmittance" },
    ],
    demonstrations: [
      "Beer-Lambert : A = f(C) est une droite (courbe d'étalonnage). Mesurer A_inconnu → lire C_inconnu sur la droite.",
      "Spectre d'identification : comparer les raies observées avec les tables de référence.",
      "Loi de Wien : étoile bleue (λ_max ≈ 400 nm) → T = 2898×10⁻³/400×10⁻⁹ ≈ 7 250 K.",
    ],
    schemas: [
      `Types de spectres :\n\n  Continu   : ████████████████████  (tous λ)\n  (corps incandescent)\n\n  Émission  : ────│────│──│─────  (raies brillantes)\n  (atome excité)\n\n  Absorption: ████│████│██│█████  (raies sombres)\n  (lumière blanche + atomes froids)\n\n→ Raies d'absorption ↔ raies d'émission\n  du MÊME élément chimique\n\nSpectrophotométrie (Beer-Lambert) :\n  A\n  │   / ← pente = ε × l\n  │  /\n  │ /\n  │/\n  └────────→ C (mol/L)`,
    ],
    tips: [
      "Courbe d'étalonnage : tracer A = f(C) à partir de solutions de concentration connue → droite si A < 1.",
      "Longueur d'onde d'analyse λmax : choisir là où l'absorbance est maximale → meilleure sensibilité.",
      "Spectre de Fraunhofer (Soleil) : raies d'absorption → identifie He, Na, etc. dans l'atmosphère solaire.",
    ],
    remember: [
      "Chaque élément a un spectre de raies unique : sa signature spectrale.",
      "Beer-Lambert : A = εlC → dosage par spectrophotométrie. A ∝ C (droite).",
      "Émission = raies brillantes sur fond sombre. Absorption = raies sombres sur fond continu.",
    ],
    extras: [],
  },
  {
    id: 19,
    title: "Méthodes physiques d'analyse",
    icon: "🔍",
    color: "#fbbf24",
    definition: "Les méthodes physiques d'analyse permettent d'identifier et de doser des composés. Au programme : spectroscopie IR (groupes fonctionnels), RMN ¹H (environnement des protons), chromatographie CCM/HPLC. Ces techniques se complètent pour déterminer une structure moléculaire.",
    formulas: [
      { name: "Déplacement chimique (RMN)", expr: "δ (ppm) = (ν_obs − ν_ref)/ν_spectromètre × 10⁶", desc: "Référence : TMS, δ = 0 ppm" },
      { name: "Multiplicité (règle n+1)", expr: "Multiplet = n+1 raies si n H voisins", desc: "Doublet = 1 voisin, triplet = 2 voisins" },
      { name: "Rf (chromatographie CCM)", expr: "Rf = d_composé / d_front_solvant", desc: "0 < Rf < 1" },
      { name: "Nombre d'onde (IR)", expr: "σ̃ = 1/λ  (cm⁻¹)", desc: "σ̃(C=O) ≈ 1700, σ̃(O-H) ≈ 3300 cm⁻¹" },
    ],
    demonstrations: [
      "IR : identifier un groupe fonctionnel par lecture du tableau des bandes d'absorption caractéristiques.",
      "RMN : déduire la structure depuis δ (environnement chimique), multiplicité (n+1), et intégration (nombre de H).",
      "CCM : Rf identique à un témoin = même composé. Rapport Rf lié à la polarité.",
    ],
    schemas: [
      `Spectroscopie IR — Bandes caractéristiques :\n\n  σ̃ (cm⁻¹)  | Liaison  | Groupe fonctionnel\n  ───────────────────────────────────────────\n  3200–3600  | O–H      | Alcool (large)\n  2500–3300  | O–H      | Acide carboxylique (très large)\n  2850–2960  | C–H      | Alcane\n  2100–2260  | C≡C, C≡N | Alcyne, nitrile\n  1700–1750  | C=O      | Cétone, aldéhyde, ester, acide\n  1600–1680  | C=C      | Alcène\n  1000–1200  | C–O      | Alcool, ester\n\nRMN ¹H — Déplacements chimiques typiques (ppm):\n  TMS (0) | CH₃ (0–1) | CH₂ (1–2) | CH (1,5–3)\n  C=C-H (4,5–6) | Ar-H (6,5–8) | CHO (9–10) | COOH (10–12)`,
    ],
    tips: [
      "IR : bande LARGE ≈ 3300 cm⁻¹ → O-H (alcool). TRÈS LARGE et étalée → O-H d'acide. Fine ≈ 1700 cm⁻¹ → C=O.",
      "RMN : triplet = 2 voisins H (ex : CH₂ adjacent à CH₃ donne un quadruplet). Intégration ∝ nombre de H.",
      "CCM : toujours comparer avec un TÉMOIN connu pour identifier. Rf ne suffit pas seul (dépend du solvant).",
    ],
    remember: [
      "IR : groupes fonctionnels via bandes d'absorption. C=O ≈ 1700, O-H ≈ 3300 cm⁻¹.",
      "RMN ¹H : δ (ppm), multiplicité (n+1), intégration (nb de H).",
      "CCM : Rf = d_composé/d_solvant. Rf identique = même composé (avec même éluant).",
    ],
    extras: [],
  },
  {
    id: 20,
    title: "Utilisation de Python pour la modélisation",
    icon: "🐍",
    color: "#38bdf8",
    definition: "Python (avec numpy, matplotlib, scipy) est utilisé en physique-chimie pour modéliser des phénomènes physiques, résoudre numériquement des équations différentielles, et analyser des données expérimentales.",
    formulas: [
      { name: "Méthode d'Euler (intégration numérique)", expr: "y(t+h) = y(t) + h × f(t, y(t))", desc: "h : pas de temps, f : fonction dérivée" },
      { name: "Régression linéaire (numpy)", expr: "coeffs = np.polyfit(x, y, 1)", desc: "coeffs[0]=pente, coeffs[1]=ordonnée" },
      { name: "Tableau de valeurs", expr: "np.linspace(a, b, n)", desc: "n points régulièrement espacés entre a et b" },
      { name: "Résolution EDO (scipy)", expr: "sol = odeint(f, y0, t)", desc: "Plus précis qu'Euler" },
    ],
    demonstrations: [
      "Résolution numérique du PFD par la méthode d'Euler : v(t+h) = v(t) + h×a(t) ; x(t+h) = x(t) + h×v(t).",
      "Tracé d'une courbe v(t) en intégrant numériquement a(t) (intégration par la méthode des rectangles).",
      "Régression linéaire sur données expérimentales : np.polyfit(x, y, 1) → pente et ordonnée à l'origine.",
    ],
    schemas: [
      `Algorithme d'Euler (ex: chute libre) :\n\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ng = 9.81    # m/s²\nh = 0.01    # pas de temps (s)\n\nt_list = [0.0]\ny_list = [0.0]   # position initiale\nv_list = [0.0]   # vitesse initiale\n\nfor i in range(1000):\n    a = -g              # accélération\n    v_new = v_list[-1] + h * a\n    y_new = y_list[-1] + h * v_list[-1]\n    t_new = t_list[-1] + h\n    v_list.append(v_new)\n    y_list.append(y_new)\n    t_list.append(t_new)\n\nplt.plot(t_list, y_list, label='y(t)')\nplt.xlabel('t (s)') ; plt.ylabel('y (m)')\nplt.title('Chute libre — Méthode d\\'Euler')\nplt.legend() ; plt.show()`,
    ],
    tips: [
      "Plus le pas h est petit → plus la simulation est précise mais plus elle est lente. Compromis typique : h ≈ 0,001 × période caractéristique.",
      "Toujours tracer et vérifier visuellement le résultat pour détecter les erreurs (courbe incohérente = bug).",
      "scipy.integrate.odeint ou solve_ivp sont plus précis et robustes qu'Euler pour les EDO difficiles.",
    ],
    remember: [
      "Méthode d'Euler : approximation numérique de la dérivée. Valable pour h suffisamment petit.",
      "numpy : calculs numériques. matplotlib : graphiques. scipy : méthodes avancées (odeint, curve_fit).",
      "Validation : comparer la simulation à la solution analytique quand elle existe.",
    ],
    extras: [],
  },
];